-- Feb 13, 2014 11:27:15 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Field (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsDisplayed CHAR(1) DEFAULT 'Y' CHECK (IsDisplayed IN ('Y','N')), IsReadOnly CHAR(1) DEFAULT 'N' CHECK (IsReadOnly IN ('Y','N')), IsSameLine CHAR(1) DEFAULT 'N' CHECK (IsSameLine IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, SeqNo NUMBER(10) DEFAULT NULL , SFA_Field_ID NUMBER(10) NOT NULL, SFA_Column_ID NUMBER(10) NOT NULL, SFA_Tab_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Field_Key PRIMARY KEY (SFA_Field_ID))
;

-- Feb 13, 2014 11:27:20 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Field_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SFA_Field_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Field_Trl_Key PRIMARY KEY (AD_Language, SFA_Field_ID))
;

-- Feb 13, 2014 11:27:26 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Menu (Action CHAR(1) DEFAULT NULL , AD_Client_ID NUMBER(10) NOT NULL, AD_Form_ID NUMBER(10) DEFAULT NULL , AD_Org_ID NUMBER(10) NOT NULL, AD_Process_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DeploymentType CHAR(1) DEFAULT NULL , Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, ErrImgUrl NVARCHAR2(60) DEFAULT NULL , GroupByClause NVARCHAR2(255) DEFAULT NULL , ImageURL NVARCHAR2(120) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT 'Y' CHECK (IsCentrallyMaintained IN ('Y','N')), IsInsertRecord CHAR(1) DEFAULT 'N' CHECK (IsInsertRecord IN ('Y','N')), IsReadWrite CHAR(1) DEFAULT 'N' CHECK (IsReadWrite IN ('Y','N')), IsSummary CHAR(1) DEFAULT 'N' CHECK (IsSummary IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, OrderByClause NVARCHAR2(2000) DEFAULT NULL , QuickActionMenu_ID NUMBER(10) DEFAULT NULL , SFA_Menu_ID NUMBER(10) NOT NULL, SFA_SyncMenu_ID NUMBER(10) DEFAULT NULL , SFA_Table_ID NUMBER(10) DEFAULT NULL , SFA_Window_ID NUMBER(10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WhereClause NVARCHAR2(2000) DEFAULT NULL , CONSTRAINT SFA_Menu_Key PRIMARY KEY (SFA_Menu_ID))
;

-- Feb 13, 2014 11:27:32 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Menu_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT NULL  CHECK (IsTranslated IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, SFA_Menu_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Menu_Trl_Key PRIMARY KEY (AD_Language, SFA_Menu_ID))
;

-- Feb 13, 2014 11:28:21 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Column (AD_Client_ID NUMBER(10) NOT NULL, AD_Column_ID NUMBER(10) DEFAULT NULL , AD_Element_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Reference_ID NUMBER(10) NOT NULL, AD_Reference_Value_ID NUMBER(10) DEFAULT NULL , AD_Val_Rule_ID NUMBER(10) DEFAULT NULL , Callout NVARCHAR2(255) DEFAULT NULL , ColumnName NVARCHAR2(30) NOT NULL, ColumnSQL NVARCHAR2(2000) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DefaultValue NVARCHAR2(2000) DEFAULT NULL , Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, FieldLength NUMBER(10) DEFAULT NULL , FormatPattern NVARCHAR2(22) DEFAULT NULL , InfoFactoryClass NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsAlwaysUpdateable CHAR(1) DEFAULT 'N' CHECK (IsAlwaysUpdateable IN ('Y','N')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT 'Y' CHECK (IsCentrallyMaintained IN ('Y','N')), IsEncrypted CHAR(1) DEFAULT 'N', IsIdentifier CHAR(1) DEFAULT 'N' CHECK (IsIdentifier IN ('Y','N')) NOT NULL, IsKey CHAR(1) DEFAULT 'N' CHECK (IsKey IN ('Y','N')) NOT NULL, IsMandatory CHAR(1) DEFAULT 'N' CHECK (IsMandatory IN ('Y','N')) NOT NULL, IsParent CHAR(1) DEFAULT 'N' CHECK (IsParent IN ('Y','N')) NOT NULL, IsSelectionColumn CHAR(1) DEFAULT 'N' CHECK (IsSelectionColumn IN ('Y','N')) NOT NULL, IsUpdateable CHAR(1) DEFAULT 'Y' CHECK (IsUpdateable IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SelectionSeqNo NUMBER(10) DEFAULT NULL , SeqNo NUMBER(10) DEFAULT NULL , SFA_Column_ID NUMBER(10) NOT NULL, SFA_Table_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, ValueMax NVARCHAR2(20) DEFAULT NULL , ValueMin NVARCHAR2(20) DEFAULT NULL , VFormat NVARCHAR2(60) DEFAULT NULL , CONSTRAINT SFA_Column_Key PRIMARY KEY (SFA_Column_ID))
;

-- Feb 13, 2014 11:28:37 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Column_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SFA_Column_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Column_Trl_Key PRIMARY KEY (AD_Language, SFA_Column_ID))
;

-- Feb 13, 2014 11:28:43 PM VET
-- SFAndroid Server
CREATE TABLE SFA_SyncMenu (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_RuleAfter_ID NUMBER(10) DEFAULT NULL , AD_RuleBefore_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, ErrImgUrl NVARCHAR2(60) DEFAULT NULL , ImageURL NVARCHAR2(120) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsSummary CHAR(1) DEFAULT 'N' CHECK (IsSummary IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SFA_SyncMenu_ID NUMBER(10) NOT NULL, SFA_Table_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WhereClause NVARCHAR2(2000) DEFAULT NULL , WS_WebService_ID NUMBER(10) DEFAULT NULL , WS_WebServiceType_ID NUMBER(10) DEFAULT NULL , CONSTRAINT SFA_SyncMenu_Key PRIMARY KEY (SFA_SyncMenu_ID))
;

-- Feb 13, 2014 11:28:48 PM VET
-- SFAndroid Server
CREATE TABLE SFA_SyncMenu_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SFA_SyncMenu_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_SyncMenu_Trl_Key PRIMARY KEY (AD_Language, SFA_SyncMenu_ID))
;

-- Feb 13, 2014 11:28:54 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Table (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Rule_ID NUMBER(10) DEFAULT NULL , AD_Table_ID NUMBER(10) DEFAULT NULL , CopyColumnsFromTable CHAR(1) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, GenerateScriptFromTable CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT 'Y' CHECK (IsCentrallyMaintained IN ('Y','N')), IsDeleteable CHAR(1) DEFAULT 'N' CHECK (IsDeleteable IN ('Y','N')), IsView CHAR(1) DEFAULT 'N' CHECK (IsView IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, SFA_Table_ID NUMBER(10) NOT NULL, TableName NVARCHAR2(40) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Table_Key PRIMARY KEY (SFA_Table_ID))
;

-- Feb 13, 2014 11:28:59 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Table_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SFA_Table_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Table_Trl_Key PRIMARY KEY (AD_Language, SFA_Table_ID))
;

-- Feb 13, 2014 11:29:04 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Tab (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Classname NVARCHAR2(60) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, Help NVARCHAR2(2000) DEFAULT NULL , ImportFields CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsReadOnly CHAR(1) DEFAULT 'N' CHECK (IsReadOnly IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, OrderByClause NVARCHAR2(2000) DEFAULT NULL , Processing CHAR(1) DEFAULT NULL , SeqNo NUMBER(10) NOT NULL, SFA_Table_ID NUMBER(10) DEFAULT NULL , SFA_Tab_ID NUMBER(10) NOT NULL, SFA_Window_ID NUMBER(10) NOT NULL, TabLevel NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WhereClause NVARCHAR2(2000) DEFAULT NULL , CONSTRAINT SFA_Tab_Key PRIMARY KEY (SFA_Tab_ID))
;

-- Feb 13, 2014 11:29:10 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Tab_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SFA_Tab_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Tab_Trl_Key PRIMARY KEY (AD_Language, SFA_Tab_ID))
;

-- Feb 13, 2014 11:29:16 PM VET
-- SFAndroid Server
CREATE TABLE SFA_UserDocSequence (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Sequence_ID NUMBER(10) NOT NULL, AD_User_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL)
;

-- Feb 13, 2014 11:29:22 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Window (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , SFA_Window_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Window_Key PRIMARY KEY (SFA_Window_ID))
;

-- Feb 13, 2014 11:29:37 PM VET
-- SFAndroid Server
CREATE TABLE SFA_Window_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SFA_Window_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SFA_Window_Trl_Key PRIMARY KEY (AD_Language, SFA_Window_ID))
;

