-- Aug 25, 2014 6:43:51 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Column (AD_Client_ID NUMBER(10) NOT NULL, AD_Column_ID NUMBER(10) DEFAULT NULL , AD_Element_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Process_ID NUMBER(10) DEFAULT NULL , AD_Reference_ID NUMBER(10) NOT NULL, AD_Reference_Value_ID NUMBER(10) DEFAULT NULL , AD_Val_Rule_ID NUMBER(10) DEFAULT NULL , Callout NVARCHAR2(255) DEFAULT NULL , ColumnName NVARCHAR2(30) NOT NULL, ColumnSQL NVARCHAR2(2000) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DefaultValue NVARCHAR2(2000) DEFAULT NULL , Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, FieldLength NUMBER(10) DEFAULT NULL , FormatPattern NVARCHAR2(22) DEFAULT NULL , InfoFactoryClass NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsAlwaysUpdateable CHAR(1) DEFAULT 'N' CHECK (IsAlwaysUpdateable IN ('Y','N')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT 'Y' CHECK (IsCentrallyMaintained IN ('Y','N')), IsEncrypted CHAR(1) DEFAULT 'N', IsIdentifier CHAR(1) DEFAULT 'N' CHECK (IsIdentifier IN ('Y','N')) NOT NULL, IsKey CHAR(1) DEFAULT 'N' CHECK (IsKey IN ('Y','N')) NOT NULL, IsMandatory CHAR(1) DEFAULT 'N' CHECK (IsMandatory IN ('Y','N')) NOT NULL, IsParent CHAR(1) DEFAULT 'N' CHECK (IsParent IN ('Y','N')) NOT NULL, IsSelectionColumn CHAR(1) DEFAULT 'N' CHECK (IsSelectionColumn IN ('Y','N')) NOT NULL, IsUpdateable CHAR(1) DEFAULT 'Y' CHECK (IsUpdateable IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SelectionSeqNo NUMBER(10) DEFAULT NULL , SeqNo NUMBER(10) DEFAULT NULL , SPS_Column_ID NUMBER(10) NOT NULL, SPS_Table_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, ValueMax NVARCHAR2(20) DEFAULT NULL , ValueMin NVARCHAR2(20) DEFAULT NULL , VFormat NVARCHAR2(60) DEFAULT NULL , CONSTRAINT SPS_Column_Key PRIMARY KEY (SPS_Column_ID))
;

-- Aug 25, 2014 6:44:21 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Column_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SPS_Column_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Column_Trl_Key PRIMARY KEY (AD_Language, SPS_Column_ID))
;

-- Aug 25, 2014 6:44:27 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Field (AD_Client_ID NUMBER(10) NOT NULL, AD_FieldGroup_ID NUMBER(10) DEFAULT NULL , AD_Org_ID NUMBER(10) NOT NULL, AD_Reference_ID NUMBER(10) DEFAULT NULL , AD_Reference_Value_ID NUMBER(10) DEFAULT NULL , AD_Val_Rule_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DefaultValue NVARCHAR2(2000) DEFAULT NULL , Description NVARCHAR2(255) DEFAULT NULL , DisplayLogic NVARCHAR2(2000) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT 'Y' CHECK (IsCentrallyMaintained IN ('Y','N')), IsDisplayed CHAR(1) DEFAULT 'Y' CHECK (IsDisplayed IN ('Y','N')), IsEncrypted CHAR(1) DEFAULT 'N' CHECK (IsEncrypted IN ('Y','N')), IsMandatory CHAR(1) DEFAULT NULL , IsReadOnly CHAR(1) DEFAULT 'N' CHECK (IsReadOnly IN ('Y','N')), IsSameLine CHAR(1) DEFAULT 'N' CHECK (IsSameLine IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, SeqNo NUMBER(10) DEFAULT NULL , SPS_Column_ID NUMBER(10) NOT NULL, SPS_Field_ID NUMBER(10) NOT NULL, SPS_Tab_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Field_Key PRIMARY KEY (SPS_Field_ID))
;

-- Aug 25, 2014 6:44:35 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Field_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SPS_Field_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Field_Trl_Key PRIMARY KEY (AD_Language, SPS_Field_ID))
;

-- Aug 25, 2014 6:44:40 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Menu (Action CHAR(1) DEFAULT NULL , ActivityMenu_ID NUMBER(10) DEFAULT NULL , AD_Client_ID NUMBER(10) NOT NULL, AD_Form_ID NUMBER(10) DEFAULT NULL , AD_Org_ID NUMBER(10) NOT NULL, AD_Process_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, DeploymentType CHAR(1) DEFAULT NULL , Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, ErrImgUrl NVARCHAR2(60) DEFAULT NULL , GroupByClause NVARCHAR2(255) DEFAULT NULL , ImageURL NVARCHAR2(120) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT 'Y' CHECK (IsCentrallyMaintained IN ('Y','N')), IsInsertRecord CHAR(1) DEFAULT 'N' CHECK (IsInsertRecord IN ('Y','N')), IsReadWrite CHAR(1) DEFAULT 'N' CHECK (IsReadWrite IN ('Y','N')), IsSummary CHAR(1) DEFAULT 'N' CHECK (IsSummary IN ('Y','N')), MenuType CHAR(1) NOT NULL, Name NVARCHAR2(60) NOT NULL, OrderByClause NVARCHAR2(2000) DEFAULT NULL , QuickActionMenu_ID NUMBER(10) DEFAULT NULL , SPS_Menu_ID NUMBER(10) NOT NULL, SPS_SyncMenu_ID NUMBER(10) DEFAULT NULL , SPS_Table_ID NUMBER(10) DEFAULT NULL , SPS_Window_ID NUMBER(10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WhereClause NVARCHAR2(2000) DEFAULT NULL , CONSTRAINT SPS_Menu_Key PRIMARY KEY (SPS_Menu_ID))
;

-- Aug 25, 2014 6:44:46 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Menu_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT NULL  CHECK (IsTranslated IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, SPS_Menu_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Menu_Trl_Key PRIMARY KEY (AD_Language, SPS_Menu_ID))
;

-- Aug 25, 2014 6:44:52 AM VET
-- Spin Suite Server
CREATE TABLE SPS_SyncMenu (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_RuleAfter_ID NUMBER(10) DEFAULT NULL , AD_RuleBefore_ID NUMBER(10) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, ErrImgUrl NVARCHAR2(60) DEFAULT NULL , ImageURL NVARCHAR2(120) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsSummary CHAR(1) DEFAULT 'N' CHECK (IsSummary IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SPS_SyncMenu_ID NUMBER(10) NOT NULL, SPS_Table_ID NUMBER(10) DEFAULT NULL , Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WhereClause NVARCHAR2(2000) DEFAULT NULL , WS_WebService_ID NUMBER(10) DEFAULT NULL , WS_WebServiceMethod_ID NUMBER(10) DEFAULT NULL , WS_WebServiceType_ID NUMBER(10) DEFAULT NULL , CONSTRAINT SPS_SyncMenu_Key PRIMARY KEY (SPS_SyncMenu_ID))
;

-- Aug 25, 2014 6:44:57 AM VET
-- Spin Suite Server
CREATE TABLE SPS_SyncMenu_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SPS_SyncMenu_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_SyncMenu_Trl_Key PRIMARY KEY (AD_Language, SPS_SyncMenu_ID))
;

-- Aug 25, 2014 6:45:02 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Tab (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Process_ID NUMBER(10) DEFAULT NULL , Classname NVARCHAR2(60) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, Help NVARCHAR2(2000) DEFAULT NULL , ImportFields CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsInsertRecord CHAR(1) DEFAULT 'N' CHECK (IsInsertRecord IN ('Y','N')), IsReadOnly CHAR(1) DEFAULT 'N' CHECK (IsReadOnly IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, OrderByClause NVARCHAR2(2000) DEFAULT NULL , Parent_Column_ID NUMBER(10) DEFAULT NULL , Processing CHAR(1) DEFAULT NULL , SeqNo NUMBER(10) NOT NULL, SPS_Column_ID NUMBER(10) DEFAULT NULL , SPS_Tab_ID NUMBER(10) NOT NULL, SPS_Table_ID NUMBER(10) DEFAULT NULL , SPS_Window_ID NUMBER(10) NOT NULL, TabLevel NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, WhereClause NVARCHAR2(2000) DEFAULT NULL , CONSTRAINT SPS_Tab_Key PRIMARY KEY (SPS_Tab_ID))
;

-- Aug 25, 2014 6:45:07 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Table (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Rule_ID NUMBER(10) DEFAULT NULL , AD_Table_ID NUMBER(10) DEFAULT NULL , CopyColumnsFromTable CHAR(1) DEFAULT NULL , Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, GenerateScriptFromTable CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT 'Y' CHECK (IsCentrallyMaintained IN ('Y','N')), IsDeleteable CHAR(1) DEFAULT 'N' CHECK (IsDeleteable IN ('Y','N')), IsView CHAR(1) DEFAULT 'N' CHECK (IsView IN ('Y','N')), Name NVARCHAR2(60) NOT NULL, SPS_Table_ID NUMBER(10) NOT NULL, TableName NVARCHAR2(40) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Table_Key PRIMARY KEY (SPS_Table_ID))
;

-- Aug 25, 2014 6:45:12 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Table_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SPS_Table_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Table_Trl_Key PRIMARY KEY (AD_Language, SPS_Table_ID))
;

-- Aug 25, 2014 6:45:17 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Tab_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SPS_Tab_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Tab_Trl_Key PRIMARY KEY (AD_Language, SPS_Tab_ID))
;

-- Aug 25, 2014 6:45:22 AM VET
-- Spin Suite Server
CREATE TABLE SPS_UserDocSequence (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Sequence_ID NUMBER(10) NOT NULL, AD_User_ID NUMBER(10) NOT NULL, C_DocType_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL)
;

-- Aug 25, 2014 6:45:28 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Window (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , EntityType VARCHAR2(40) DEFAULT 'ECA01' NOT NULL, Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , SPS_Window_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Window_Key PRIMARY KEY (SPS_Window_ID))
;

-- Aug 25, 2014 6:45:35 AM VET
-- Spin Suite Server
CREATE TABLE SPS_Window_Trl (AD_Client_ID NUMBER(10) NOT NULL, AD_Language VARCHAR2(6) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, Description NVARCHAR2(255) DEFAULT NULL , Help NVARCHAR2(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsTranslated CHAR(1) DEFAULT 'N' CHECK (IsTranslated IN ('Y','N')) NOT NULL, Name NVARCHAR2(60) NOT NULL, SPS_Window_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Window_Trl_Key PRIMARY KEY (AD_Language, SPS_Window_ID))
;

-- Sep 10, 2014 8:43:49 PM CEST
-- Spin-Suite
CREATE TABLE SPS_Window_Access (AD_Client_ID NUMBER(10) NOT NULL, AD_Org_ID NUMBER(10) NOT NULL, AD_Role_ID NUMBER(10) NOT NULL, Created DATE NOT NULL, CreatedBy NUMBER(10) NOT NULL, IsActive CHAR(1) DEFAULT 'Y' CHECK (IsActive IN ('Y','N')) NOT NULL, IsReadWrite CHAR(1) CHECK (IsReadWrite IN ('Y','N')) NOT NULL, SPS_Window_ID NUMBER(10) NOT NULL, Updated DATE NOT NULL, UpdatedBy NUMBER(10) NOT NULL, CONSTRAINT SPS_Window_Access_Key PRIMARY KEY (AD_Role_ID, SPS_Window_ID))
;

-- Oct 23, 2014 4:41:41 PM CEST
-- Spin-Suite
ALTER TABLE SPS_Menu ADD IsSOTrx CHAR(1) DEFAULT 'N' CHECK (IsSOTrx IN ('Y','N')) NOT NULL
;

-- Oct 23, 2014 4:42:15 PM CEST
-- Spin-Suite
ALTER TABLE SPS_Table ADD AccessLevel CHAR(1) DEFAULT '4' NOT NULL
;

-- Oct 23, 2014 4:42:38 PM CEST
-- Spin-Suite
ALTER TABLE SPS_Window ADD IsSOTrx CHAR(1) DEFAULT 'N' CHECK (IsSOTrx IN ('Y','N')) NOT NULL
;
