ALTER Table SPS_Column ADD CONSTRAINT 
fk_SPS_Column_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table (SPS_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER Table SPS_Column ADD CONSTRAINT 
CONSTRAINT SPS_Column_AD_Column FOREIGN KEY (AD_Column_ID)
REFERENCES AD_Column (AD_Column_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SPS_Column_Trl ADD CONSTRAINT FK_SPS_Column_Trl_SPS_Column 
FOREIGN KEY (SPS_Column_ID)
REFERENCES SPS_Column (SPS_Column_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_AD_Form FOREIGN KEY (AD_Form_ID)
REFERENCES AD_Form (AD_Form_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_AD_RuleAfter FOREIGN KEY (AD_RuleAfter_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_AD_RuleBefore FOREIGN KEY (AD_RuleBefore_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table (SPS_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SPS_Table ADD CONSTRAINT FK_SPS_Table_AD_Rule FOREIGN KEY (AD_Rule_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Table ADD CONSTRAINT  FK_SPS_Table_AD_Table FOREIGN KEY (AD_Table_ID)
REFERENCES AD_Table (AD_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Table ADD CONSTRAINT  FK_SPS_Table_Trl_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table (SPS_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE,


CONSTRAINT fk_sf_userdocsequence_ad_sequence FOREIGN KEY (ad_sequence_id)
REFERENCES ad_sequence (ad_sequence_id) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_sf_userdocsequence_c_doctype FOREIGN KEY (c_doctype_id)
REFERENCES c_doctype (c_doctype_id) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_sf_userdocsequence_salesrep FOREIGN KEY (salesrep_id)
REFERENCES ad_user (ad_user_id) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE,


ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_AD_Form FOREIGN KEY (AD_Form_ID)
REFERENCES AD_Form (AD_Form_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_AD_RuleAfter FOREIGN KEY (AD_RuleAfter_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_RuleBefore FOREIGN KEY (AD_RuleBefore_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table (SPS_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;
