ALTER Table SFA_Column ADD CONSTRAINT 
fk_SFA_Column_SFA_Table FOREIGN KEY (SFA_Table_ID)
REFERENCES SFA_Table (SFA_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER Table SFA_Column ADD CONSTRAINT 
CONSTRAINT SFA_Column_AD_Column FOREIGN KEY (AD_Column_ID)
REFERENCES AD_Column (AD_Column_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SFA_Column_Trl ADD CONSTRAINT FK_SFA_Column_Trl_SFA_Column 
FOREIGN KEY (SFA_Column_ID)
REFERENCES SFA_Column (SFA_Column_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SFA_SyncMenu ADD CONSTRAINT FK_SFA_SyncMenu_AD_Form FOREIGN KEY (AD_Form_ID)
REFERENCES AD_Form (AD_Form_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SFA_SyncMenu ADD CONSTRAINT FK_SFA_SyncMenu_AD_RuleAfter FOREIGN KEY (AD_RuleAfter_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SFA_SyncMenu ADD CONSTRAINT FK_SFA_SyncMenu_AD_RuleBefore FOREIGN KEY (AD_RuleBefore_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SFA_SyncMenu ADD CONSTRAINT FK_SFA_SyncMenu_SFA_Table FOREIGN KEY (SFA_Table_ID)
REFERENCES SFA_Table (SFA_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SFA_Table ADD CONSTRAINT FK_SFA_Table_AD_Rule FOREIGN KEY (AD_Rule_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SFA_Table ADD CONSTRAINT  FK_SFA_Table_AD_Table FOREIGN KEY (AD_Table_ID)
REFERENCES AD_Table (AD_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SFA_Table ADD CONSTRAINT  FK_SFA_Table_Trl_SFA_Table FOREIGN KEY (SFA_Table_ID)
REFERENCES SFA_Table (SFA_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE,


CONSTRAINT fk_sf_userdocsequence_ad_sequence FOREIGN KEY (ad_sequence_id)
REFERENCES ad_sequence (ad_sequence_id) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_sf_userdocsequence_c_doctype FOREIGN KEY (c_doctype_id)
REFERENCES c_doctype (c_doctype_id) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT fk_sf_userdocsequence_salesrep FOREIGN KEY (salesrep_id)
REFERENCES ad_user (ad_user_id) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE,


ALTER TABLE SFA_Menu ADD CONSTRAINT FK_SFA_Menu_AD_Form FOREIGN KEY (AD_Form_ID)
REFERENCES AD_Form (AD_Form_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SFA_Menu ADD CONSTRAINT FK_SFA_Menu_AD_RuleAfter FOREIGN KEY (AD_RuleAfter_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SFA_Menu ADD CONSTRAINT FK_SFA_Menu_RuleBefore FOREIGN KEY (AD_RuleBefore_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SFA_Menu ADD CONSTRAINT FK_SFA_Menu_SFA_Table FOREIGN KEY (SFA_Table_ID)
REFERENCES SFA_Table (SFA_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;
