-- Sep 15, 2014 4:31:36 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50021,TO_DATE('2014-09-15 16:31:28','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Tree','Q','CREATE TABLE AD_Tree (AD_Client_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, AD_Table_ID NUMBERIC(10) DEFAULT NULL , AD_Tree_ID NUMBERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsAllNodes CHAR(1) CHECK (IsAllNodes IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) DEFAULT ''N'' CHECK (IsDefault IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , TreeType VARCHAR(2) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, CONSTRAINT AD_Tree_Key PRIMARY KEY (AD_Tree_ID))',TO_DATE('2014-09-15 16:31:28','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Tree')
;

-- Sep 15, 2014 4:31:36 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50021,Updated=TO_DATE('2014-09-15 16:31:36','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50063
;

-- Sep 15, 2014 4:45:54 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50022,TO_DATE('2014-09-15 16:45:48','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Attachment','Q','CREATE TABLE AD_Attachment (AD_Attachment_ID NUMBERIC(10) NOT NULL, AD_Client_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, AD_Table_ID NUMBERIC(10) NOT NULL, BinaryData TEXT DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Record_ID NUMBERIC(10) NOT NULL, TextMsg VARCHAR(2000) DEFAULT NULL , Title VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, CONSTRAINT AD_Attachment_Key PRIMARY KEY (AD_Attachment_ID))',TO_DATE('2014-09-15 16:45:48','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Attachment')
;

-- Sep 15, 2014 4:45:54 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50022,Updated=TO_DATE('2014-09-15 16:45:54','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50097
;

-- Sep 15, 2014 4:46:38 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50023,TO_DATE('2014-09-15 16:46:31','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Client','Q','CREATE TABLE AD_Client (AD_Client_ID NUMBERIC(10) NOT NULL, AD_Language VARCHAR(6) DEFAULT NULL , AD_Org_ID NUMBERIC(10) NOT NULL, AD_ReplicationStrategy_ID NUMBERIC(10) DEFAULT NULL , AutoArchive CHAR(1) DEFAULT ''N'' NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) DEFAULT 0 NOT NULL, Description VARCHAR(255) DEFAULT NULL , DocumentDir VARCHAR(60) DEFAULT NULL , EMailTest CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCostImmediate CHAR(1) DEFAULT ''N'' CHECK (IsCostImmediate IN (''Y'',''N'')) NOT NULL, IsMultiLingualDocument CHAR(1) CHECK (IsMultiLingualDocument IN (''Y'',''N'')) NOT NULL, IsPostImmediate CHAR(1) DEFAULT ''N'' CHECK (IsPostImmediate IN (''Y'',''N'')) NOT NULL, IsServerEMail CHAR(1) CHECK (IsServerEMail IN (''Y'',''N'')) NOT NULL, IsSmtpAuthorization CHAR(1) DEFAULT ''N'' CHECK (IsSmtpAuthorization IN (''Y'',''N'')) NOT NULL, IsUseASP CHAR(1) DEFAULT ''N'' CHECK (IsUseASP IN (''Y'',''N'')) NOT NULL, IsUseBetaFunctions CHAR(1) DEFAULT ''Y'' CHECK (IsUseBetaFunctions IN (''Y'',''N'')) NOT NULL, MMPolicy CHAR(1) DEFAULT ''F'' NOT NULL, ModelValidationClasses VARCHAR(255) DEFAULT NULL , Name VARCHAR(60) NOT NULL, RequestEMail VARCHAR(60) DEFAULT NULL , RequestFolder VARCHAR(20) DEFAULT NULL , RequestUser VARCHAR(60) DEFAULT NULL , RequestUserPW VARCHAR(20) DEFAULT NULL , SMTPHost VARCHAR(60) DEFAULT NULL , StoreArchiveOnFileSystem CHAR(1) CHECK (StoreArchiveOnFileSystem IN (''Y'',''N'')) NOT NULL, StoreAttachmentsOnFileSystem CHAR(1) CHECK (StoreAttachmentsOnFileSystem IN (''Y'',''N'')) NOT NULL, UnixArchivePath VARCHAR(255) DEFAULT NULL , UnixAttachmentPath VARCHAR(255) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, WindowsArchivePath VARCHAR(255) DEFAULT NULL , WindowsAttachmentPath VARCHAR(255) DEFAULT NULL , CONSTRAINT AD_Client_Key PRIMARY KEY (AD_Client_ID))',TO_DATE('2014-09-15 16:46:31','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Client')
;

-- Sep 15, 2014 4:46:38 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50023,Updated=TO_DATE('2014-09-15 16:46:38','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50098
;

-- Sep 15, 2014 4:46:44 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50024,TO_DATE('2014-09-15 16:46:43','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Document Action Access','Q','CREATE TABLE AD_Document_Action_Access (AD_Client_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, AD_Ref_List_ID NUMBERIC(10) NOT NULL, AD_Role_ID NUMBERIC(10) NOT NULL, C_DocType_ID NUMBERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, IsActive CHAR(1) CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, CONSTRAINT AD_Document_Action_Access_Key PRIMARY KEY (AD_Ref_List_ID, AD_Role_ID, C_DocType_ID))',TO_DATE('2014-09-15 16:46:43','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Document_Action_Access')
;

-- Sep 15, 2014 4:46:44 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50024,Updated=TO_DATE('2014-09-15 16:46:44','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50069
;

-- Sep 15, 2014 4:46:59 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50025,TO_DATE('2014-09-15 16:46:57','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table System Element','Q','CREATE TABLE AD_Element (AD_Client_ID NUMBERIC(10) NOT NULL, AD_Element_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, AD_Reference_ID NUMBERIC(10) DEFAULT NULL , AD_Reference_Value_ID NUMBERIC(10) DEFAULT NULL , ColumnName VARCHAR(30) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''U'' NOT NULL, FieldLength NUMBERIC(10) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, PO_Description VARCHAR(255) DEFAULT NULL , PO_Help VARCHAR(2000) DEFAULT NULL , PO_Name VARCHAR(60) DEFAULT NULL , PO_PrintName VARCHAR(60) DEFAULT NULL , PrintName VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, CONSTRAINT AD_Element_Key PRIMARY KEY (AD_Element_ID))',TO_DATE('2014-09-15 16:46:57','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Element')
;

-- Sep 15, 2014 4:46:59 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50025,Updated=TO_DATE('2014-09-15 16:46:59','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50096
;

-- Sep 15, 2014 4:47:17 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50026,TO_DATE('2014-09-15 16:47:08','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Entity Type','Q','CREATE TABLE AD_EntityType (AD_Client_ID NUMBERIC(10) DEFAULT 0 NOT NULL, AD_EntityType_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) DEFAULT 0 NOT NULL, Classpath VARCHAR(255) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) NOT NULL, Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) CHECK (IsActive IN (''Y'',''N'')) NOT NULL, ModelPackage VARCHAR(255) DEFAULT NULL , Name VARCHAR(120) NOT NULL, Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, Version VARCHAR(20) DEFAULT NULL , CONSTRAINT AD_EntityType_Key PRIMARY KEY (AD_EntityType_ID))',TO_DATE('2014-09-15 16:47:08','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_EntityType')
;

-- Sep 15, 2014 4:47:17 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50026,Updated=TO_DATE('2014-09-15 16:47:17','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50085
;

-- Sep 15, 2014 5:02:28 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50027,TO_DATE('2014-09-15 17:02:21','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Special Form','Q','CREATE TABLE AD_Form (AccessLevel CHAR(1) NOT NULL, AD_Client_ID NUMBERIC(10) NOT NULL, AD_Form_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, Classname VARCHAR(60) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''U'' NOT NULL, Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsBetaFunctionality CHAR(1) CHECK (IsBetaFunctionality IN (''Y'',''N'')) NOT NULL, IsDefinedForMobile CHAR(1) DEFAULT ''N'' CHECK (IsDefinedForMobile IN (''Y'',''N'')), JSPURL VARCHAR(120) DEFAULT NULL , Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, CONSTRAINT AD_Form_Key PRIMARY KEY (AD_Form_ID))',TO_DATE('2014-09-15 17:02:21','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Form')
;

-- Sep 15, 2014 5:02:28 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50027,Updated=TO_DATE('2014-09-15 17:02:28','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50073
;

-- Sep 15, 2014 5:02:57 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50028,TO_DATE('2014-09-15 17:02:55','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table AD_Form_Access','Q','CREATE TABLE AD_Form_Access (AD_Client_ID NUMBERIC(10) NOT NULL, AD_Form_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, AD_Role_ID NUMBERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsReadWrite CHAR(1) CHECK (IsReadWrite IN (''Y'',''N'')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, CONSTRAINT AD_Form_Access_Key PRIMARY KEY (AD_Form_ID, AD_Role_ID))',TO_DATE('2014-09-15 17:02:55','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Form_Access')
;

-- Sep 15, 2014 5:02:57 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50028,Updated=TO_DATE('2014-09-15 17:02:57','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50068
;

-- Sep 15, 2014 5:04:12 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50029,TO_DATE('2014-09-15 17:04:05','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Special Form Trl','Q','CREATE TABLE AD_Form_Trl (AD_Client_ID NUMBERIC(10) NOT NULL, AD_Form_ID NUMBERIC(10) NOT NULL, AD_Language VARCHAR(6) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsTranslated CHAR(1) CHECK (IsTranslated IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, CONSTRAINT AD_Form_Trl_Key PRIMARY KEY (AD_Form_ID, AD_Language))',TO_DATE('2014-09-15 17:04:05','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Form_Trl')
;

-- Sep 15, 2014 5:04:12 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50029,Updated=TO_DATE('2014-09-15 17:04:12','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50074
;

-- Sep 15, 2014 5:04:21 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50030,TO_DATE('2014-09-15 17:04:16','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Organization','Q','CREATE TABLE AD_Org (AD_Client_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, AD_ReplicationStrategy_ID NUMBERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsSummary CHAR(1) CHECK (IsSummary IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, CONSTRAINT AD_Org_Key PRIMARY KEY (AD_Org_ID))',TO_DATE('2014-09-15 17:04:16','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Org')
;

-- Sep 15, 2014 5:04:21 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50030,Updated=TO_DATE('2014-09-15 17:04:21','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50099
;

-- Sep 15, 2014 5:04:34 PM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50031,TO_DATE('2014-09-15 17:04:32','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Print Color','Q','CREATE TABLE AD_PrintColor (AD_Client_ID NUMBERIC(10) NOT NULL, AD_Org_ID NUMBERIC(10) NOT NULL, AD_PrintColor_ID NUMBERIC(10) NOT NULL, Code VARCHAR(2000) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMBERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) CHECK (IsDefault IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMBERIC(10) NOT NULL, CONSTRAINT AD_PrintColor_Key PRIMARY KEY (AD_PrintColor_ID))',TO_DATE('2014-09-15 17:04:32','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_PrintColor')
;

-- Sep 15, 2014 5:04:34 PM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50031,Updated=TO_DATE('2014-09-15 17:04:34','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50091
;

