-- Sep 19, 2014 11:18:10 AM VET
-- SPS
INSERT INTO AD_Rule (AccessLevel,AD_Client_ID,AD_Org_ID,AD_Rule_ID,Created,CreatedBy,EntityType,EventType,IsActive,Name,RuleType,Script,Updated,UpdatedBy,Value) VALUES ('4',0,0,50120,TO_DATE('2014-09-19 11:18:04','YYYY-MM-DD HH24:MI:SS'),100,'ECA01','P','Y','Rule Create Table Column','Q','CREATE TABLE AD_Column (AD_Client_ID NUMERIC(10) NOT NULL, AD_Column_ID NUMERIC(10) NOT NULL, AD_Element_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Process_ID NUMERIC(10) DEFAULT NULL , AD_Reference_ID NUMERIC(10) NOT NULL, AD_Reference_Value_ID NUMERIC(10) DEFAULT NULL , AD_Table_ID NUMERIC(10) NOT NULL, AD_Val_Rule_ID NUMERIC(10) DEFAULT NULL , Callout VARCHAR(255) DEFAULT NULL , ColumnName VARCHAR(30) NOT NULL, ColumnSQL VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DefaultValue VARCHAR(2000) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''U'' NOT NULL, FieldLength NUMBERIC(10) DEFAULT NULL , FormatPattern VARCHAR(22) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , InfoFactoryClass VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsAllowLogging CHAR(1) DEFAULT ''Y'' CHECK (IsAllowLogging IN (''Y'',''N'')), IsAlwaysUpdateable CHAR(1) DEFAULT ''N'' CHECK (IsAlwaysUpdateable IN (''Y'',''N'')) NOT NULL, IsAutocomplete CHAR(1) DEFAULT ''N'' CHECK (IsAutocomplete IN (''Y'',''N'')) NOT NULL, IsEncrypted CHAR(1) DEFAULT ''N'' NOT NULL, IsIdentifier CHAR(1) CHECK (IsIdentifier IN (''Y'',''N'')) NOT NULL, IsKey CHAR(1) CHECK (IsKey IN (''Y'',''N'')) NOT NULL, IsMandatory CHAR(1) CHECK (IsMandatory IN (''Y'',''N'')) NOT NULL, IsParent CHAR(1) CHECK (IsParent IN (''Y'',''N'')) NOT NULL, IsSelectionColumn CHAR(1) CHECK (IsSelectionColumn IN (''Y'',''N'')) NOT NULL, IsSyncDatabase CHAR(1) DEFAULT NULL , IsTranslated CHAR(1) CHECK (IsTranslated IN (''Y'',''N'')) NOT NULL, IsUpdateable CHAR(1) DEFAULT ''Y'' CHECK (IsUpdateable IN (''Y'',''N'')) NOT NULL, MandatoryLogic VARCHAR(2000) DEFAULT NULL , Name VARCHAR(60) NOT NULL, ReadOnlyLogic VARCHAR(2000) DEFAULT NULL , SeqNo NUMBERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValueMax VARCHAR(20) DEFAULT NULL , ValueMin VARCHAR(20) DEFAULT NULL , Version NUMBER NOT NULL, VFormat VARCHAR(60) DEFAULT NULL , CONSTRAINT AD_Column_Key PRIMARY KEY (AD_Column_ID))',TO_DATE('2014-09-19 11:18:04','YYYY-MM-DD HH24:MI:SS'),100,'SQL:Create_AD_Column')
;

-- Sep 19, 2014 11:18:10 AM VET
-- SPS
UPDATE SPS_Table SET AD_Rule_ID=50120,Updated=TO_DATE('2014-09-19 11:18:10','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_Table_ID=50224
;

