ALTER TABLE SPS_Table_Trl ADD CONSTRAINT FK_SPS_Table_Trl_AD_Language FOREIGN KEY (AD_Language)
REFERENCES AD_Language(AD_Language) 
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SPS_Table ADD CONSTRAINT FK_SPS_Table_EntityType FOREIGN KEY (EntityType)
REFERENCES AD_EntityType(EntityType) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Table ADD CONSTRAINT FK_SPS_Table_AD_Rule FOREIGN KEY (AD_Rule_ID)
REFERENCES AD_Rule (AD_Rule_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Table ADD CONSTRAINT  FK_SPS_Table_AD_Table FOREIGN KEY (AD_Table_ID)
REFERENCES AD_Table (AD_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Table ADD CONSTRAINT  FK_SPS_Table_Trl_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table (SPS_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER Table SPS_Column ADD CONSTRAINT SPS_Column_AD_Column FOREIGN KEY (AD_Column_ID)
REFERENCES AD_Column (AD_Column_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Column_Trl ADD CONSTRAINT FK_SPS_Column_Trl_SPS_Column FOREIGN KEY (SPS_Column_ID)
REFERENCES SPS_Column (SPS_Column_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER Table SPS_Column ADD CONSTRAINT FK_SPS_Column_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table (SPS_Table_ID) MATCH SIMPLE
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SPS_Column ADD CONSTRAINT FK_SPS_Column_AD_Reference_Value FOREIGN KEY (AD_Reference_Value_ID)
REFERENCES AD_Reference(AD_Reference_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Column ADD CONSTRAINT FK_SPS_Column_AD_Element FOREIGN KEY (AD_Element_ID)
REFERENCES AD_Element(AD_Element_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Column ADD CONSTRAINT FK_SPS_Column_AD_Column FOREIGN KEY (AD_Column_ID)
REFERENCES AD_Column(AD_Column_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Column ADD CONSTRAINT FK_SPS_Column_AD_Val_Rule FOREIGN KEY (AD_Val_Rule_ID)
REFERENCES AD_Val_Rule(AD_Val_Rule_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Column ADD CONSTRAINT FK_SPS_Column_AD_Reference FOREIGN KEY (AD_Reference_ID)
REFERENCES AD_Reference(AD_Reference_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Column ADD CONSTRAINT FK_SPS_Column_EntityType FOREIGN KEY (EntityType)
REFERENCES AD_EntityType(EntityType) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Column_Trl ADD CONSTRAINT FK_SPS_Column_Trl_AD_Language FOREIGN KEY (AD_Language)
REFERENCES AD_Language(AD_Language) 
ON UPDATE CASCADE ON DELETE RESTRICT;


ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table(SPS_Table_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_AD_RuleAfter FOREIGN KEY (AD_RuleAfter_ID)
REFERENCES AD_Rule(AD_Rule_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_AD_RuleBefore FOREIGN KEY (AD_RuleBefore_ID)
REFERENCES AD_Rule(AD_Rule_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_EntityType FOREIGN KEY (EntityType)
REFERENCES AD_EntityType(EntityType) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_WS_WebService FOREIGN KEY (WS_WebService_ID)
REFERENCES WS_WebService(WS_WebService_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_WS_WebServiceType FOREIGN KEY (WS_WebServiceType_ID)
REFERENCES WS_WebServiceType(WS_WebServiceType_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu ADD CONSTRAINT FK_SPS_SyncMenu_WS_WebServiceMethod FOREIGN KEY (WS_WebServiceMethod_ID)
REFERENCES WS_WebServiceMethod(WS_WebServiceMethod_ID) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE SPS_SyncMenu_Trl ADD CONSTRAINT FK_SPS_SyncMenu_Trl_SPS_SyncMenu FOREIGN KEY (SPS_SyncMenu_ID)
REFERENCES SPS_SyncMenu(SPS_SyncMenu_ID) 
ON UPDATE CASCADE 
ON DELETE CASCADE;

ALTER TABLE SPS_SyncMenu_Trl ADD CONSTRAINT FK_SPS_SyncMenu_Trl_AD_Language FOREIGN KEY (AD_Language)
REFERENCES AD_Language(AD_Language) 
ON UPDATE CASCADE 
ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_EntityType FOREIGN KEY (EntityType)
REFERENCES AD_EntityType(EntityType) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_AD_Form FOREIGN KEY (AD_Form_ID)
REFERENCES AD_Form(AD_Form_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_QuickActionMenu FOREIGN KEY (QuickActionMenu_ID)
REFERENCES SPS_Menu(SPS_Menu_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_AD_Process FOREIGN KEY (AD_Process_ID)
REFERENCES AD_Process(AD_Process_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_SPS_Window FOREIGN KEY (SPS_Window_ID)
REFERENCES SPS_Window(SPS_Window_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table(SPS_Table_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu ADD CONSTRAINT FK_SPS_Menu_SPS_SyncMenu FOREIGN KEY (SPS_SyncMenu_ID)
REFERENCES SPS_SyncMenu(SPS_SyncMenu_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu_Trl ADD CONSTRAINT FK_SPS_Menu_Trl_AD_Language FOREIGN KEY (AD_Language)
REFERENCES AD_Language(AD_Language) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Menu_Trl ADD CONSTRAINT FK_SPS_Menu_Trl_SPS_Menu FOREIGN KEY (SPS_Menu_ID)
REFERENCES SPS_Menu(SPS_Menu_ID) 
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SPS_Window ADD CONSTRAINT FK_SPS_Window_EntityType FOREIGN KEY (EntityType)
REFERENCES AD_EntityType(EntityType) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Window_Trl ADD CONSTRAINT FK_SPS_Window_Trl_SPS_Window FOREIGN KEY (SPS_Window_ID)
REFERENCES SPS_Window(SPS_Window_ID) 
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SPS_Tab ADD CONSTRAINT FK_SPS_Tab_SPS_Table FOREIGN KEY (SPS_Table_ID)
REFERENCES SPS_Table(SPS_Table_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Tab ADD CONSTRAINT FK_SPS_Tab_SPS_Window FOREIGN KEY (SPS_Window_ID)
REFERENCES SPS_Window(SPS_Window_ID) 
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SPS_Tab ADD CONSTRAINT FK_SPS_Tab_EntityType FOREIGN KEY (EntityType)
REFERENCES AD_EntityType(EntityType) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Tab_Trl ADD CONSTRAINT FK_SPS_Tab_Trl_SPS_Tab FOREIGN KEY (SPS_Tab_ID)
REFERENCES SPS_Tab(SPS_Tab_ID) 
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SPS_Field ADD CONSTRAINT FK_SPS_Field_EntityType FOREIGN KEY (EntityType)
REFERENCES AD_EntityType(EntityType) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Field ADD CONSTRAINT FK_SPS_Field_SPS_Column FOREIGN KEY (SPS_Column_ID)
REFERENCES SPS_Column(SPS_Column_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_Field ADD CONSTRAINT FK_SPS_Field_SPS_Tab FOREIGN KEY (SPS_Tab_ID)
REFERENCES SPS_Tab(SPS_Tab_ID) 
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SPS_Field_Trl ADD CONSTRAINT FK_SPS_Field_Trl_SPS_Field FOREIGN KEY (SPS_Field_ID)
REFERENCES SPS_Field(SPS_Field_ID) 
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE SPS_UserDocSequence ADD CONSTRAINT FK_SPS_UserDocSequence_C_DocType FOREIGN KEY (C_DocType_ID)
REFERENCES C_DocType(C_DocType_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_UserDocSequence ADD CONSTRAINT FK_SPS_UserDocSequence_AD_User FOREIGN KEY (AD_User_ID)
REFERENCES AD_User(AD_User_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE SPS_UserDocSequence ADD CONSTRAINT FK_SPS_UserDocSequence_AD_Sequence FOREIGN KEY (AD_Sequence_ID)
REFERENCES AD_Sequence(AD_Sequence_ID) 
ON UPDATE CASCADE ON DELETE RESTRICT;
