-- Mar 20, 2015 8:43:22 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_TreeNode (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Tree_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Node_ID NUMERIC(10) NOT NULL, Parent_ID NUMERIC(10) DEFAULT NULL , SeqNo NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_TreeNode_Key PRIMARY KEY (AD_Tree_ID, Node_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50146
;

-- Mar 20, 2015 8:43:22 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Process (AccessLevel CHAR(1) NOT NULL, AD_Browse_ID NUMERIC(10) DEFAULT NULL , AD_Client_ID NUMERIC(10) NOT NULL, AD_Form_ID NUMERIC(10) DEFAULT NULL , AD_Org_ID NUMERIC(10) NOT NULL, AD_PrintFormat_ID NUMERIC(10) DEFAULT NULL , AD_Process_ID NUMERIC(10) NOT NULL, AD_ReportView_ID NUMERIC(10) DEFAULT NULL , AD_Workflow_ID NUMERIC(10) DEFAULT NULL , Classname VARCHAR(255) DEFAULT NULL , CopyFromProcess CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''U'' NOT NULL, Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsBetaFunctionality CHAR(1) CHECK (IsBetaFunctionality IN (''Y'',''N'')) NOT NULL, IsDefinedForMobile CHAR(1) DEFAULT ''N'' CHECK (IsDefinedForMobile IN (''Y'',''N'')), IsDirectPrint CHAR(1) DEFAULT NULL  CHECK (IsDirectPrint IN (''Y'',''N'')), IsReport CHAR(1) CHECK (IsReport IN (''Y'',''N'')) NOT NULL, IsServerProcess CHAR(1) CHECK (IsServerProcess IN (''Y'',''N'')) NOT NULL, JasperReport VARCHAR(255) DEFAULT NULL , Name VARCHAR(60) NOT NULL, ProcedureName VARCHAR(60) DEFAULT NULL , ShowHelp CHAR(1) DEFAULT ''Y'', Statistic_Count NUMERIC(10) DEFAULT NULL , Statistic_Seconds NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, WorkflowValue VARCHAR(40) DEFAULT NULL , CONSTRAINT AD_Process_Key PRIMARY KEY (AD_Process_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50157
;

-- Mar 20, 2015 8:43:22 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Process_Para (AD_Client_ID NUMERIC(10) NOT NULL, AD_Element_ID NUMERIC(10) DEFAULT NULL , AD_Org_ID NUMERIC(10) NOT NULL, AD_Process_ID NUMERIC(10) NOT NULL, AD_Process_Para_ID NUMERIC(10) NOT NULL, AD_Reference_ID NUMERIC(10) NOT NULL, AD_Reference_Value_ID NUMERIC(10) DEFAULT NULL , AD_Val_Rule_ID NUMERIC(10) DEFAULT NULL , ColumnName VARCHAR(30) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DefaultValue VARCHAR(2000) DEFAULT NULL , DefaultValue2 VARCHAR(2000) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , DisplayLogic VARCHAR(2000) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''U'' NOT NULL, FieldLength NUMERIC(10) NOT NULL, Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT ''Y'' CHECK (IsCentrallyMaintained IN (''Y'',''N'')) NOT NULL, IsMandatory CHAR(1) CHECK (IsMandatory IN (''Y'',''N'')) NOT NULL, IsRange CHAR(1) CHECK (IsRange IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, ReadOnlyLogic VARCHAR(2000) DEFAULT NULL , SeqNo NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValueMax VARCHAR(20) DEFAULT NULL , ValueMin VARCHAR(20) DEFAULT NULL , VFormat VARCHAR(20) DEFAULT NULL , CONSTRAINT AD_Process_Para_Key PRIMARY KEY (AD_Process_Para_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50159
;

-- Mar 20, 2015 8:43:22 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Sequence (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Sequence_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CurrentNext NUMERIC(10) DEFAULT 1000000 NOT NULL, CurrentNextSys NUMERIC(10) DEFAULT 100 NOT NULL, DateColumn VARCHAR(60) DEFAULT NULL , DecimalPattern VARCHAR(40) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , IncrementNo NUMERIC(10) DEFAULT 1 NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')), IsAudited CHAR(1) DEFAULT NULL  CHECK (IsAudited IN (''Y'',''N'')), IsAutoSequence CHAR(1) CHECK (IsAutoSequence IN (''Y'',''N'')) NOT NULL, IsTableID CHAR(1) DEFAULT NULL  CHECK (IsTableID IN (''Y'',''N'')), Name VARCHAR(60) NOT NULL, Prefix VARCHAR(255) DEFAULT NULL , StartNewYear CHAR(1) DEFAULT NULL  CHECK (StartNewYear IN (''Y'',''N'')), StartNo NUMERIC(10) DEFAULT 1000000 NOT NULL, Suffix VARCHAR(255) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, VFormat VARCHAR(40) DEFAULT NULL , CONSTRAINT AD_Sequence_Key PRIMARY KEY (AD_Sequence_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50161
;

-- Mar 20, 2015 8:43:22 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_PrintFormat (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_PrintColor_ID NUMERIC(10) NOT NULL, AD_PrintFont_ID NUMERIC(10) NOT NULL, AD_PrintFormat_ID NUMERIC(10) DEFAULT 0 NOT NULL, AD_PrintPaper_ID NUMERIC(10) NOT NULL, AD_PrintTableFormat_ID NUMERIC(10) DEFAULT NULL , AD_ReportView_ID NUMERIC(10) DEFAULT NULL , AD_Table_ID NUMERIC(10) DEFAULT NULL , Args VARCHAR(510) DEFAULT NULL , Classname VARCHAR(255) DEFAULT NULL , CreateCopy CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , FooterMargin NUMERIC(10) NOT NULL, HeaderMargin NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) CHECK (IsDefault IN (''Y'',''N'')) NOT NULL, IsDefinedForMobile CHAR(1) DEFAULT ''N'' CHECK (IsDefinedForMobile IN (''Y'',''N'')), IsForm CHAR(1) CHECK (IsForm IN (''Y'',''N'')) NOT NULL, IsStandardHeaderFooter CHAR(1) DEFAULT ''Y'' CHECK (IsStandardHeaderFooter IN (''Y'',''N'')) NOT NULL, IsTableBased CHAR(1) DEFAULT ''Y'' CHECK (IsTableBased IN (''Y'',''N'')) NOT NULL, JasperProcess_ID NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) NOT NULL, PrinterName VARCHAR(40) DEFAULT NULL , SPS_Table_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_PrintFormat_Key PRIMARY KEY (AD_PrintFormat_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50169
;

-- Mar 20, 2015 8:43:22 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_PrintFormatItem (AD_Client_ID NUMERIC(10) NOT NULL, AD_Column_ID NUMERIC(10) DEFAULT NULL , AD_Org_ID NUMERIC(10) NOT NULL, AD_PrintColor_ID NUMERIC(10) DEFAULT NULL , AD_PrintFont_ID NUMERIC(10) DEFAULT NULL , AD_PrintFormatChild_ID NUMERIC(10) NOT NULL, AD_PrintFormat_ID NUMERIC(10) NOT NULL, AD_PrintFormatItem_ID NUMERIC(10) NOT NULL, AD_PrintGraph_ID NUMERIC(10) DEFAULT NULL , ArcDiameter NUMERIC(10) DEFAULT 0, BarcodeType VARCHAR(3) DEFAULT NULL , BelowColumn NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, FieldAlignmentType CHAR(1) DEFAULT ''D'' NOT NULL, FormatPattern VARCHAR(22) DEFAULT NULL , ImageIsAttached CHAR(1) CHECK (ImageIsAttached IN (''Y'',''N'')) NOT NULL, ImageURL VARCHAR(120) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsAveraged CHAR(1) CHECK (IsAveraged IN (''Y'',''N'')) NOT NULL, IsCentrallyMaintained CHAR(1) CHECK (IsCentrallyMaintained IN (''Y'',''N'')) NOT NULL, IsCounted CHAR(1) CHECK (IsCounted IN (''Y'',''N'')) NOT NULL, IsDeviationCalc CHAR(1) CHECK (IsDeviationCalc IN (''Y'',''N'')) NOT NULL, IsFilledRectangle CHAR(1) DEFAULT ''N'' CHECK (IsFilledRectangle IN (''Y'',''N'')) NOT NULL, IsFixedWidth CHAR(1) CHECK (IsFixedWidth IN (''Y'',''N'')) NOT NULL, IsGroupBy CHAR(1) CHECK (IsGroupBy IN (''Y'',''N'')) NOT NULL, IsHeightOneLine CHAR(1) DEFAULT ''Y'' CHECK (IsHeightOneLine IN (''Y'',''N'')) NOT NULL, IsImageField CHAR(1) CHECK (IsImageField IN (''Y'',''N'')) NOT NULL, IsMaxCalc CHAR(1) CHECK (IsMaxCalc IN (''Y'',''N'')) NOT NULL, IsMinCalc CHAR(1) CHECK (IsMinCalc IN (''Y'',''N'')) NOT NULL, IsNextLine CHAR(1) DEFAULT ''Y'' CHECK (IsNextLine IN (''Y'',''N'')) NOT NULL, IsNextPage CHAR(1) CHECK (IsNextPage IN (''Y'',''N'')) NOT NULL, IsOrderBy CHAR(1) CHECK (IsOrderBy IN (''Y'',''N'')) NOT NULL, IsPageBreak CHAR(1) CHECK (IsPageBreak IN (''Y'',''N'')) NOT NULL, IsPrinted CHAR(1) DEFAULT ''Y'' CHECK (IsPrinted IN (''Y'',''N'')) NOT NULL, IsRelativePosition CHAR(1) DEFAULT ''Y'' CHECK (IsRelativePosition IN (''Y'',''N'')) NOT NULL, IsRunningTotal CHAR(1) CHECK (IsRunningTotal IN (''Y'',''N'')) NOT NULL, IsSetNLPosition CHAR(1) CHECK (IsSetNLPosition IN (''Y'',''N'')) NOT NULL, IsSummarized CHAR(1) CHECK (IsSummarized IN (''Y'',''N'')) NOT NULL, IsSuppressNull CHAR(1) CHECK (IsSuppressNull IN (''Y'',''N'')) NOT NULL, IsSuppressRepeats CHAR(1) DEFAULT ''N'' CHECK (IsSuppressRepeats IN (''Y'',''N'')) NOT NULL, IsVarianceCalc CHAR(1) CHECK (IsVarianceCalc IN (''Y'',''N'')) NOT NULL, LineAlignmentType CHAR(1) DEFAULT ''X'' NOT NULL, LineWidth NUMERIC(10) DEFAULT 1, MaxHeight NUMERIC(10) NOT NULL, MaxWidth NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, PrintAreaType CHAR(1) DEFAULT ''C'' NOT NULL, PrintFormatType CHAR(1) DEFAULT ''F'' NOT NULL, PrintName VARCHAR(2000) DEFAULT NULL , PrintNameSuffix VARCHAR(60) DEFAULT NULL , RunningTotalLines NUMERIC(10) DEFAULT 20, SeqNo NUMERIC(10) NOT NULL, ShapeType CHAR(1) DEFAULT ''N'', SortNo NUMERIC(10) NOT NULL, SPS_Column_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, XPosition NUMERIC(10) NOT NULL, XSpace NUMERIC(10) NOT NULL, YPosition NUMERIC(10) NOT NULL, YSpace NUMERIC(10) NOT NULL, CONSTRAINT AD_PrintFormatItem_Key PRIMARY KEY (AD_PrintFormatItem_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50170
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_PrintPaper (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_PrintPaper_ID NUMERIC(10) NOT NULL, Code VARCHAR(2000) DEFAULT ''iso-a4'' NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , DimensionUnits CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) CHECK (IsDefault IN (''Y'',''N'')) NOT NULL, IsLandscape CHAR(1) DEFAULT ''Y'' CHECK (IsLandscape IN (''Y'',''N'')) NOT NULL, MarginBottom NUMERIC(10) DEFAULT 36 NOT NULL, MarginLeft NUMERIC(10) DEFAULT 36 NOT NULL, MarginRight NUMERIC(10) DEFAULT 36 NOT NULL, MarginTop NUMERIC(10) DEFAULT 36 NOT NULL, Name VARCHAR(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , SizeX NUMBER DEFAULT NULL , SizeY NUMBER DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_PrintPaper_Key PRIMARY KEY (AD_PrintPaper_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50174
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Element (AD_Client_ID NUMERIC(10) NOT NULL, AD_Element_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Reference_ID NUMERIC(10) DEFAULT NULL , AD_Reference_Value_ID NUMERIC(10) DEFAULT NULL , ColumnName VARCHAR(30) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''U'' NOT NULL, FieldLength NUMERIC(10) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, PO_Description VARCHAR(255) DEFAULT NULL , PO_Help VARCHAR(2000) DEFAULT NULL , PO_Name VARCHAR(60) DEFAULT NULL , PO_PrintName VARCHAR(60) DEFAULT NULL , PrintName VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_Element_Key PRIMARY KEY (AD_Element_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50178
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Attachment (AD_Attachment_ID NUMERIC(10) NOT NULL, AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Table_ID NUMERIC(10) NOT NULL, BinaryData TEXT DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Record_ID NUMERIC(10) NOT NULL, TextMsg VARCHAR(2000) DEFAULT NULL , Title VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_Attachment_Key PRIMARY KEY (AD_Attachment_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50179
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE C_DocType (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_PrintFormat_ID NUMERIC(10) DEFAULT 0, C_DocTypeDifference_ID NUMERIC(10) DEFAULT NULL , C_DocType_ID NUMERIC(10) NOT NULL, C_DocTypeInvoice_ID NUMERIC(10) DEFAULT NULL , C_DocTypeProforma_ID NUMERIC(10) DEFAULT NULL , C_DocTypeShipment_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DefiniteSequence_ID NUMERIC(10) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , DocBaseType VARCHAR(3) NOT NULL, DocNoSequence_ID NUMERIC(10) DEFAULT NULL , DocSubTypeSO VARCHAR(2) DEFAULT NULL , DocumentCopies NUMERIC(10) DEFAULT 1 NOT NULL, DocumentNote VARCHAR(2000) DEFAULT NULL , GL_Category_ID NUMERIC(10) NOT NULL, HasCharges CHAR(1) CHECK (HasCharges IN (''Y'',''N'')) NOT NULL, HasProforma CHAR(1) DEFAULT NULL  CHECK (HasProforma IN (''Y'',''N'')), IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCreateCounter CHAR(1) DEFAULT ''Y'' CHECK (IsCreateCounter IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) CHECK (IsDefault IN (''Y'',''N'')) NOT NULL, IsDefaultCounterDoc CHAR(1) CHECK (IsDefaultCounterDoc IN (''Y'',''N'')) NOT NULL, IsDocNoControlled CHAR(1) DEFAULT ''Y'' CHECK (IsDocNoControlled IN (''Y'',''N'')) NOT NULL, IsIndexed CHAR(1) CHECK (IsIndexed IN (''Y'',''N'')) NOT NULL, IsInTransit CHAR(1) CHECK (IsInTransit IN (''Y'',''N'')) NOT NULL, IsOverwriteDateOnComplete CHAR(1) DEFAULT ''N'' CHECK (IsOverwriteDateOnComplete IN (''Y'',''N'')), IsOverwriteSeqOnComplete CHAR(1) DEFAULT ''N'' CHECK (IsOverwriteSeqOnComplete IN (''Y'',''N'')), IsPickQAConfirm CHAR(1) CHECK (IsPickQAConfirm IN (''Y'',''N'')) NOT NULL, IsPrepareSplitDocument CHAR(1) DEFAULT ''Y'' CHECK (IsPrepareSplitDocument IN (''Y'',''N'')) NOT NULL, IsShipConfirm CHAR(1) CHECK (IsShipConfirm IN (''Y'',''N'')) NOT NULL, IsSOTrx CHAR(1) CHECK (IsSOTrx IN (''Y'',''N'')) NOT NULL, IsSplitWhenDifference CHAR(1) DEFAULT ''N'' CHECK (IsSplitWhenDifference IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, PrintName VARCHAR(60) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT C_DocType_Key PRIMARY KEY (C_DocType_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50183
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE SPS_SyncMenu (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_RuleAfter_ID NUMERIC(10) DEFAULT NULL , AD_RuleBefore_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''ECA01'' NOT NULL, ErrImgUrl VARCHAR(60) DEFAULT NULL , ImageURL VARCHAR(120) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsSummary CHAR(1) DEFAULT ''N'' CHECK (IsSummary IN (''Y'',''N'')) NOT NULL, IsSynchronized CHAR(1) DEFAULT ''N'' CHECK (IsSynchronized IN (''Y'',''N'')), LastSynchronized TIMESTAMP DEFAULT NULL , Name VARCHAR(60) NOT NULL, Processing CHAR(1) DEFAULT NULL , SPS_SyncMenu_ID NUMERIC(10) NOT NULL, SPS_Table_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WhereClause VARCHAR(2000) DEFAULT NULL , WS_WebService_ID NUMERIC(10) DEFAULT NULL , WS_WebServiceMethod_ID NUMERIC(10) DEFAULT NULL , WS_WebServiceType_ID NUMERIC(10) DEFAULT NULL , CONSTRAINT SPS_SyncMenu_Key PRIMARY KEY (SPS_SyncMenu_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50185
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE SPS_Table (AccessLevel CHAR(1) DEFAULT ''4'' NOT NULL, AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Rule_ID NUMERIC(10) DEFAULT NULL , AD_Table_ID NUMERIC(10) DEFAULT NULL , CopyColumnsFromTable CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''ECA01'' NOT NULL, GenerateScriptFromTable CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT ''Y'' CHECK (IsCentrallyMaintained IN (''Y'',''N'')), IsChangeLog CHAR(1) DEFAULT ''Y'' CHECK (IsChangeLog IN (''Y'',''N'')), IsDeleteable CHAR(1) DEFAULT ''N'' CHECK (IsDeleteable IN (''Y'',''N'')), IsView CHAR(1) DEFAULT ''N'' CHECK (IsView IN (''Y'',''N'')), Name VARCHAR(60) NOT NULL, SPS_Table_ID NUMERIC(10) NOT NULL, TableName VARCHAR(40) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT SPS_Table_Key PRIMARY KEY (SPS_Table_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50190
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE SPS_Column (AD_Client_ID NUMERIC(10) NOT NULL, AD_Column_ID NUMERIC(10) DEFAULT NULL , AD_Element_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Process_ID NUMERIC(10) DEFAULT NULL , AD_Reference_ID NUMERIC(10) NOT NULL, AD_Reference_Value_ID NUMERIC(10) DEFAULT NULL , AD_Val_Rule_ID NUMERIC(10) DEFAULT NULL , Callout VARCHAR(255) DEFAULT NULL , ColumnName VARCHAR(30) NOT NULL, ColumnSQL VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DefaultValue VARCHAR(2000) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''ECA01'' NOT NULL, FieldLength NUMERIC(10) DEFAULT NULL , FormatPattern VARCHAR(22) DEFAULT NULL , InfoFactoryClass VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsAllowLogging CHAR(1) DEFAULT ''Y'' CHECK (IsAllowLogging IN (''Y'',''N'')), IsAlwaysUpdateable CHAR(1) DEFAULT ''N'' CHECK (IsAlwaysUpdateable IN (''Y'',''N'')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT ''Y'' CHECK (IsCentrallyMaintained IN (''Y'',''N'')), IsEncrypted CHAR(1) DEFAULT ''N'', IsIdentifier CHAR(1) DEFAULT ''N'' CHECK (IsIdentifier IN (''Y'',''N'')) NOT NULL, IsKey CHAR(1) DEFAULT ''N'' CHECK (IsKey IN (''Y'',''N'')) NOT NULL, IsMandatory CHAR(1) DEFAULT ''N'' CHECK (IsMandatory IN (''Y'',''N'')) NOT NULL, IsParent CHAR(1) DEFAULT ''N'' CHECK (IsParent IN (''Y'',''N'')) NOT NULL, IsSelectionColumn CHAR(1) DEFAULT ''N'' CHECK (IsSelectionColumn IN (''Y'',''N'')) NOT NULL, IsUpdateable CHAR(1) DEFAULT ''Y'' CHECK (IsUpdateable IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, SelectionSeqNo NUMERIC(10) DEFAULT NULL , SeqNo NUMERIC(10) DEFAULT NULL , SPS_Column_ID NUMERIC(10) NOT NULL, SPS_Table_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValueMax VARCHAR(20) DEFAULT NULL , ValueMin VARCHAR(20) DEFAULT NULL , VFormat VARCHAR(60) DEFAULT NULL , CONSTRAINT SPS_Column_Key PRIMARY KEY (SPS_Column_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50192
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Table (AccessLevel CHAR(1) DEFAULT ''4'' NOT NULL, AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Table_ID NUMERIC(10) NOT NULL, AD_Val_Rule_ID NUMERIC(10) DEFAULT NULL , AD_Window_ID NUMERIC(10) DEFAULT NULL , CopyColumnsFromTable CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''U'' NOT NULL, Help VARCHAR(2000) DEFAULT NULL , ImportTable CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT ''Y'' CHECK (IsCentrallyMaintained IN (''Y'',''N'')), IsChangeLog CHAR(1) CHECK (IsChangeLog IN (''Y'',''N'')) NOT NULL, IsDeleteable CHAR(1) DEFAULT ''Y'' CHECK (IsDeleteable IN (''Y'',''N'')) NOT NULL, IsHighVolume CHAR(1) CHECK (IsHighVolume IN (''Y'',''N'')) NOT NULL, IsSecurityEnabled CHAR(1) CHECK (IsSecurityEnabled IN (''Y'',''N'')) NOT NULL, IsView CHAR(1) DEFAULT ''N'' CHECK (IsView IN (''Y'',''N'')) NOT NULL, LoadSeq NUMERIC(10) DEFAULT NULL , Name VARCHAR(60) NOT NULL, PO_Window_ID NUMERIC(10) DEFAULT NULL , ReplicationType CHAR(1) DEFAULT ''L'' NOT NULL, TableName VARCHAR(40) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_Table_Key PRIMARY KEY (AD_Table_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50195
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Role (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Role_ID NUMERIC(10) NOT NULL, AD_Tree_Menu_ID NUMERIC(10) DEFAULT NULL , AD_Tree_Org_ID NUMERIC(10) DEFAULT NULL , Allow_Info_Account CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_Account IN (''Y'',''N'')) NOT NULL, Allow_Info_Asset CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_Asset IN (''Y'',''N'')) NOT NULL, Allow_Info_BPartner CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_BPartner IN (''Y'',''N'')) NOT NULL, Allow_Info_CashJournal CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_CashJournal IN (''Y'',''N'')) NOT NULL, Allow_Info_CRP CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_CRP IN (''Y'',''N'')) NOT NULL, Allow_Info_InOut CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_InOut IN (''Y'',''N'')) NOT NULL, Allow_Info_Invoice CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_Invoice IN (''Y'',''N'')) NOT NULL, Allow_Info_MRP CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_MRP IN (''Y'',''N'')) NOT NULL, Allow_Info_Order CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_Order IN (''Y'',''N'')) NOT NULL, Allow_Info_Payment CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_Payment IN (''Y'',''N'')) NOT NULL, Allow_Info_Product CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_Product IN (''Y'',''N'')) NOT NULL, Allow_Info_Resource CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_Resource IN (''Y'',''N'')) NOT NULL, Allow_Info_Schedule CHAR(1) DEFAULT ''Y'' CHECK (Allow_Info_Schedule IN (''Y'',''N'')) NOT NULL, AmtApproval NUMBER DEFAULT NULL , C_Currency_ID NUMERIC(10) DEFAULT NULL , ConfirmQueryRecords NUMERIC(10) DEFAULT 0 NOT NULL, ConnectionProfile CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsAccessAllOrgs CHAR(1) DEFAULT ''N'' CHECK (IsAccessAllOrgs IN (''Y'',''N'')) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCanApproveOwnDoc CHAR(1) CHECK (IsCanApproveOwnDoc IN (''Y'',''N'')) NOT NULL, IsCanExport CHAR(1) DEFAULT ''Y'' CHECK (IsCanExport IN (''Y'',''N'')) NOT NULL, IsCanReport CHAR(1) DEFAULT ''Y'' CHECK (IsCanReport IN (''Y'',''N'')) NOT NULL, IsChangeLog CHAR(1) DEFAULT ''N'' CHECK (IsChangeLog IN (''Y'',''N'')) NOT NULL, IsDiscountAllowedOnTotal CHAR(1) CHECK (IsDiscountAllowedOnTotal IN (''Y'',''N'')) NOT NULL, IsDiscountUptoLimitPrice CHAR(1) CHECK (IsDiscountUptoLimitPrice IN (''Y'',''N'')) NOT NULL, IsManual CHAR(1) CHECK (IsManual IN (''Y'',''N'')) NOT NULL, IsPersonalAccess CHAR(1) DEFAULT ''N'' CHECK (IsPersonalAccess IN (''Y'',''N'')) NOT NULL, IsPersonalLock CHAR(1) DEFAULT ''N'' CHECK (IsPersonalLock IN (''Y'',''N'')) NOT NULL, IsShowAcct CHAR(1) DEFAULT ''N'' CHECK (IsShowAcct IN (''Y'',''N'')) NOT NULL, IsUseUserOrgAccess CHAR(1) DEFAULT ''N'' CHECK (IsUseUserOrgAccess IN (''Y'',''N'')) NOT NULL, MaxQueryRecords NUMERIC(10) DEFAULT 0 NOT NULL, Name VARCHAR(60) NOT NULL, OverwritePriceLimit CHAR(1) DEFAULT ''N'' CHECK (OverwritePriceLimit IN (''Y'',''N'')) NOT NULL, PreferenceType CHAR(1) DEFAULT ''O'' NOT NULL, Supervisor_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, UserDiscount NUMBER DEFAULT NULL , UserLevel VARCHAR(3) DEFAULT ''O'' NOT NULL, CONSTRAINT AD_Role_Key PRIMARY KEY (AD_Role_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50147
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Column (AD_Client_ID NUMERIC(10) NOT NULL, AD_Column_ID NUMERIC(10) NOT NULL, AD_Element_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Process_ID NUMERIC(10) DEFAULT NULL , AD_Reference_ID NUMERIC(10) NOT NULL, AD_Reference_Value_ID NUMERIC(10) DEFAULT NULL , AD_Table_ID NUMERIC(10) NOT NULL, AD_Val_Rule_ID NUMERIC(10) DEFAULT NULL , Callout VARCHAR(255) DEFAULT NULL , ColumnName VARCHAR(30) NOT NULL, ColumnSQL VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DefaultValue VARCHAR(2000) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''U'' NOT NULL, FieldLength NUMERIC(10) DEFAULT NULL , FormatPattern VARCHAR(22) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , InfoFactoryClass VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsAllowLogging CHAR(1) DEFAULT ''Y'' CHECK (IsAllowLogging IN (''Y'',''N'')), IsAlwaysUpdateable CHAR(1) DEFAULT ''N'' CHECK (IsAlwaysUpdateable IN (''Y'',''N'')) NOT NULL, IsAutocomplete CHAR(1) DEFAULT ''N'' CHECK (IsAutocomplete IN (''Y'',''N'')) NOT NULL, IsEncrypted CHAR(1) DEFAULT ''N'' NOT NULL, IsIdentifier CHAR(1) CHECK (IsIdentifier IN (''Y'',''N'')) NOT NULL, IsKey CHAR(1) CHECK (IsKey IN (''Y'',''N'')) NOT NULL, IsMandatory CHAR(1) CHECK (IsMandatory IN (''Y'',''N'')) NOT NULL, IsParent CHAR(1) CHECK (IsParent IN (''Y'',''N'')) NOT NULL, IsSelectionColumn CHAR(1) CHECK (IsSelectionColumn IN (''Y'',''N'')) NOT NULL, IsSyncDatabase CHAR(1) DEFAULT NULL , IsTranslated CHAR(1) CHECK (IsTranslated IN (''Y'',''N'')) NOT NULL, IsUpdateable CHAR(1) DEFAULT ''Y'' CHECK (IsUpdateable IN (''Y'',''N'')) NOT NULL, MandatoryLogic VARCHAR(2000) DEFAULT NULL , Name VARCHAR(60) NOT NULL, ReadOnlyLogic VARCHAR(2000) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, ValueMax VARCHAR(20) DEFAULT NULL , ValueMin VARCHAR(20) DEFAULT NULL , VFormat VARCHAR(60) DEFAULT NULL , CONSTRAINT AD_Column_Key PRIMARY KEY (AD_Column_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50197
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE SPS_Tab (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Process_ID NUMERIC(10) DEFAULT NULL , Classname VARCHAR(60) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''ECA01'' NOT NULL, Help VARCHAR(2000) DEFAULT NULL , ImportFields CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsInsertRecord CHAR(1) DEFAULT ''N'' CHECK (IsInsertRecord IN (''Y'',''N'')), IsReadOnly CHAR(1) DEFAULT ''N'' CHECK (IsReadOnly IN (''Y'',''N'')), Name VARCHAR(60) NOT NULL, OrderByClause VARCHAR(2000) DEFAULT NULL , Parent_Column_ID NUMERIC(10) DEFAULT NULL , Processing CHAR(1) DEFAULT NULL , SeqNo NUMERIC(10) NOT NULL, SPS_Column_ID NUMERIC(10) DEFAULT NULL , SPS_Tab_ID NUMERIC(10) NOT NULL, SPS_Table_ID NUMERIC(10) DEFAULT NULL , SPS_Window_ID NUMERIC(10) NOT NULL, TabLevel NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WhereClause VARCHAR(2000) DEFAULT NULL , CONSTRAINT SPS_Tab_Key PRIMARY KEY (SPS_Tab_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50202
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE C_PaymentTerm (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AfterDelivery CHAR(1) CHECK (AfterDelivery IN (''Y'',''N'')) NOT NULL, C_PaymentTerm_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , Discount NUMBER NOT NULL, Discount2 NUMBER NOT NULL, DiscountDays NUMERIC(10) NOT NULL, DiscountDays2 NUMERIC(10) NOT NULL, DocumentNote VARCHAR(2000) DEFAULT NULL , FixMonthCutoff NUMERIC(10) DEFAULT NULL , FixMonthDay NUMERIC(10) DEFAULT NULL , FixMonthOffset NUMERIC(10) DEFAULT NULL , GraceDays NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) DEFAULT NULL  CHECK (IsDefault IN (''Y'',''N'')), IsDueFixed CHAR(1) CHECK (IsDueFixed IN (''Y'',''N'')) NOT NULL, IsNextBusinessDay CHAR(1) DEFAULT NULL  CHECK (IsNextBusinessDay IN (''Y'',''N'')), IsValid CHAR(1) CHECK (IsValid IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, NetDay CHAR(1) DEFAULT NULL , NetDays NUMERIC(10) NOT NULL, Processing CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, CONSTRAINT C_PaymentTerm_Key PRIMARY KEY (C_PaymentTerm_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50260
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE SPS_Field (AD_Client_ID NUMERIC(10) NOT NULL, AD_FieldGroup_ID NUMERIC(10) DEFAULT NULL , AD_Org_ID NUMERIC(10) NOT NULL, AD_Reference_ID NUMERIC(10) DEFAULT NULL , AD_Reference_Value_ID NUMERIC(10) DEFAULT NULL , AD_Val_Rule_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DefaultValue VARCHAR(2000) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , DisplayLogic VARCHAR(2000) DEFAULT NULL , EntityType VARCHAR(40) DEFAULT ''ECA01'' NOT NULL, Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCentrallyMaintained CHAR(1) DEFAULT ''Y'' CHECK (IsCentrallyMaintained IN (''Y'',''N'')), IsDisplayed CHAR(1) DEFAULT ''Y'' CHECK (IsDisplayed IN (''Y'',''N'')), IsEncrypted CHAR(1) DEFAULT ''N'' CHECK (IsEncrypted IN (''Y'',''N'')), IsMandatory CHAR(1) DEFAULT NULL , IsReadOnly CHAR(1) DEFAULT ''N'' CHECK (IsReadOnly IN (''Y'',''N'')), IsSameLine CHAR(1) DEFAULT ''N'' CHECK (IsSameLine IN (''Y'',''N'')), Name VARCHAR(60) NOT NULL, SeqNo NUMERIC(10) DEFAULT NULL , SPS_Column_ID NUMERIC(10) NOT NULL, SPS_Field_ID NUMERIC(10) NOT NULL, SPS_Tab_ID NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT SPS_Field_Key PRIMARY KEY (SPS_Field_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50204
;

-- Mar 20, 2015 8:43:23 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE WS_WebService (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, NameSpace VARCHAR(120) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, WS_WebService_ID NUMERIC(10) NOT NULL, CONSTRAINT WS_WebService_Key PRIMARY KEY (WS_WebService_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50206
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE WS_WebServiceMethod (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, SeqNo NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, WS_WebService_ID NUMERIC(10) DEFAULT NULL , WS_WebServiceMethod_ID NUMERIC(10) NOT NULL, CONSTRAINT WS_WebServiceMethod_Key PRIMARY KEY (WS_WebServiceMethod_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50209
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_Issue (A_Asset_ID NUMERIC(10) DEFAULT NULL , AD_Client_ID NUMERIC(10) NOT NULL, AD_Form_ID NUMERIC(10) DEFAULT NULL , AD_Issue_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Process_ID NUMERIC(10) DEFAULT NULL , AD_Window_ID NUMERIC(10) DEFAULT NULL , Comments VARCHAR(2000) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, DatabaseInfo VARCHAR(255) DEFAULT NULL , DBAddress VARCHAR(255) DEFAULT NULL , ErrorTrace VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsReproducible CHAR(1) DEFAULT NULL , IssueSource CHAR(1) DEFAULT NULL , IssueSummary VARCHAR(2000) NOT NULL, IsVanillaSystem CHAR(1) DEFAULT NULL , JavaInfo VARCHAR(255) DEFAULT NULL , LineNo NUMERIC(10) DEFAULT NULL , Local_Host VARCHAR(120) DEFAULT NULL , LoggerName VARCHAR(60) DEFAULT NULL , Name VARCHAR(120) DEFAULT ''.'' NOT NULL, OperatingSystemInfo VARCHAR(255) DEFAULT NULL , ProfileInfo VARCHAR(255) DEFAULT NULL , Record_ID NUMERIC(10) DEFAULT 1, ReleaseNo VARCHAR(10) DEFAULT ''.'' NOT NULL, ReleaseTag VARCHAR(60) DEFAULT NULL , RequestDocumentNo VARCHAR(30) DEFAULT NULL , ResponseText VARCHAR(2000) DEFAULT NULL , R_Request_ID NUMERIC(10) DEFAULT NULL , SourceClassName VARCHAR(60) DEFAULT NULL , SourceMethodName VARCHAR(60) DEFAULT NULL , StackTrace VARCHAR(2000) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, UserName VARCHAR(60) DEFAULT ''.'' NOT NULL, CONSTRAINT AD_Issue_Key PRIMARY KEY (AD_Issue_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50212
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE C_BPartner (AcqusitionCost NUMBER DEFAULT NULL , ActualLifeTimeValue NUMBER DEFAULT NULL , AD_Client_ID NUMERIC(10) NOT NULL, AD_Language VARCHAR(6) DEFAULT NULL , AD_OrgBP_ID NUMERIC(10) DEFAULT NULL , AD_Org_ID NUMERIC(10) NOT NULL, BPartner_Parent_ID NUMERIC(10) DEFAULT NULL , C_BPartner_ID NUMERIC(10) NOT NULL, C_BP_Group_ID NUMERIC(10) NOT NULL, C_Dunning_ID NUMERIC(10) DEFAULT NULL , C_Greeting_ID NUMERIC(10) DEFAULT NULL , C_InvoiceSchedule_ID NUMERIC(10) DEFAULT NULL , C_PaymentTerm_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_TaxGroup_ID NUMERIC(10) DEFAULT NULL , DeliveryRule CHAR(1) DEFAULT NULL , DeliveryViaRule CHAR(1) DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , DocumentCopies NUMERIC(10) DEFAULT NULL , DunningGrace TIMESTAMP DEFAULT NULL , DUNS VARCHAR(11) DEFAULT NULL , FirstSale TIMESTAMP DEFAULT NULL , FlatDiscount NUMBER DEFAULT NULL , FreightCostRule CHAR(1) DEFAULT NULL , Invoice_PrintFormat_ID NUMERIC(10) DEFAULT NULL , InvoiceRule CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCustomer CHAR(1) DEFAULT ''N'' CHECK (IsCustomer IN (''Y'',''N'')) NOT NULL, IsDiscountPrinted CHAR(1) DEFAULT NULL  CHECK (IsDiscountPrinted IN (''Y'',''N'')), IsEmployee CHAR(1) DEFAULT ''N'' CHECK (IsEmployee IN (''Y'',''N'')) NOT NULL, IsManufacturer CHAR(1) DEFAULT ''N'' CHECK (IsManufacturer IN (''Y'',''N'')), IsOneTime CHAR(1) DEFAULT ''N'' CHECK (IsOneTime IN (''Y'',''N'')) NOT NULL, IsPOTaxExempt CHAR(1) DEFAULT ''N'' CHECK (IsPOTaxExempt IN (''Y'',''N'')) NOT NULL, IsProspect CHAR(1) DEFAULT ''N'' CHECK (IsProspect IN (''Y'',''N'')) NOT NULL, IsSalesRep CHAR(1) DEFAULT ''N'' CHECK (IsSalesRep IN (''Y'',''N'')) NOT NULL, IsSummary CHAR(1) DEFAULT ''N'' CHECK (IsSummary IN (''Y'',''N'')) NOT NULL, IsTaxExempt CHAR(1) DEFAULT NULL  CHECK (IsTaxExempt IN (''Y'',''N'')), IsVendor CHAR(1) DEFAULT ''N'' CHECK (IsVendor IN (''Y'',''N'')) NOT NULL, Logo_ID NUMERIC(10) DEFAULT NULL , M_DiscountSchema_ID NUMERIC(10) DEFAULT NULL , M_PriceList_ID NUMERIC(10) DEFAULT NULL , NAICS VARCHAR(6) DEFAULT NULL , Name VARCHAR(60) NOT NULL, Name2 VARCHAR(60) DEFAULT NULL , NumberEmployees NUMERIC(10) DEFAULT NULL , PaymentRule CHAR(1) DEFAULT NULL , PaymentRulePO CHAR(1) DEFAULT NULL , PO_DiscountSchema_ID NUMERIC(10) DEFAULT NULL , PO_PaymentTerm_ID NUMERIC(10) DEFAULT NULL , PO_PriceList_ID NUMERIC(10) DEFAULT NULL , POReference VARCHAR(20) DEFAULT NULL , PotentialLifeTimeValue NUMBER DEFAULT NULL , Rating VARCHAR(1) DEFAULT NULL , ReferenceNo VARCHAR(40) DEFAULT NULL , SalesRep_ID NUMERIC(10) DEFAULT NULL , SalesVolume NUMERIC(10) DEFAULT NULL , SendEMail CHAR(1) DEFAULT ''N'' CHECK (SendEMail IN (''Y'',''N'')) NOT NULL, ShareOfCustomer NUMERIC(10) DEFAULT NULL , ShelfLifeMinPct NUMERIC(10) DEFAULT NULL , SO_CreditLimit NUMBER NOT NULL, SOCreditStatus CHAR(1) DEFAULT NULL , SO_CreditUsed NUMBER NOT NULL, SO_Description VARCHAR(255) DEFAULT NULL , TaxID VARCHAR(20) DEFAULT NULL , TotalOpenBalance NUMBER DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, URL VARCHAR(120) DEFAULT NULL , Value VARCHAR(40) NOT NULL, CONSTRAINT C_BPartner_Key PRIMARY KEY (C_BPartner_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50218
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE C_Currency (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_Currency_ID NUMERIC(10) NOT NULL, CostingPrecision NUMERIC(10) DEFAULT 4 NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, CurSymbol VARCHAR(10) DEFAULT NULL , Description VARCHAR(255) NOT NULL, EMUEntryDate TIMESTAMP DEFAULT NULL , EMURate NUMBER DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsEMUMember CHAR(1) DEFAULT ''N'' CHECK (IsEMUMember IN (''Y'',''N'')) NOT NULL, IsEuro CHAR(1) DEFAULT ''N'' CHECK (IsEuro IN (''Y'',''N'')) NOT NULL, ISO_Code VARCHAR(3) NOT NULL, RoundOffFactor NUMBER DEFAULT 1 NOT NULL, StdPrecision NUMERIC(10) DEFAULT 2 NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT C_Currency_Key PRIMARY KEY (C_Currency_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50222
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE C_UOM (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, CostingPrecision NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) CHECK (IsDefault IN (''Y'',''N'')) NOT NULL, Name VARCHAR(60) NOT NULL, StdPrecision NUMERIC(10) NOT NULL, UOMSymbol VARCHAR(10) DEFAULT NULL , UOMType VARCHAR(2) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, X12DE355 VARCHAR(4) NOT NULL, CONSTRAINT C_UOM_Key PRIMARY KEY (C_UOM_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50230
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE M_Product (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Classification VARCHAR(12) DEFAULT NULL , CopyFrom CHAR(1) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_RevenueRecognition_ID NUMERIC(10) DEFAULT NULL , C_SubscriptionType_ID NUMERIC(10) DEFAULT NULL , C_TaxCategory_ID NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , DescriptionURL VARCHAR(120) DEFAULT NULL , Discontinued CHAR(1) DEFAULT NULL  CHECK (Discontinued IN (''Y'',''N'')), DiscontinuedAt TIMESTAMP DEFAULT NULL , DocumentNote VARCHAR(2000) DEFAULT NULL , Group1 VARCHAR(255) DEFAULT NULL , Group2 VARCHAR(255) DEFAULT NULL , GuaranteeDays NUMERIC(10) DEFAULT NULL , GuaranteeDaysMin NUMERIC(10) DEFAULT NULL , Help VARCHAR(2000) DEFAULT NULL , ImageURL VARCHAR(120) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsBOM CHAR(1) DEFAULT ''N'' CHECK (IsBOM IN (''Y'',''N'')) NOT NULL, IsDropShip CHAR(1) CHECK (IsDropShip IN (''Y'',''N'')) NOT NULL, IsExcludeAutoDelivery CHAR(1) DEFAULT ''N'' CHECK (IsExcludeAutoDelivery IN (''Y'',''N'')) NOT NULL, IsInvoicePrintDetails CHAR(1) CHECK (IsInvoicePrintDetails IN (''Y'',''N'')) NOT NULL, IsPickListPrintDetails CHAR(1) CHECK (IsPickListPrintDetails IN (''Y'',''N'')) NOT NULL, IsPurchased CHAR(1) DEFAULT ''Y'' CHECK (IsPurchased IN (''Y'',''N'')) NOT NULL, IsSelfService CHAR(1) DEFAULT ''Y'' CHECK (IsSelfService IN (''Y'',''N'')) NOT NULL, IsSold CHAR(1) DEFAULT ''Y'' CHECK (IsSold IN (''Y'',''N'')) NOT NULL, IsStocked CHAR(1) DEFAULT ''Y'' CHECK (IsStocked IN (''Y'',''N'')) NOT NULL, IsSummary CHAR(1) CHECK (IsSummary IN (''Y'',''N'')) NOT NULL, IsVerified CHAR(1) DEFAULT ''N'' CHECK (IsVerified IN (''Y'',''N'')) NOT NULL, IsWebStoreFeatured CHAR(1) CHECK (IsWebStoreFeatured IN (''Y'',''N'')) NOT NULL, LowLevel NUMERIC(10) DEFAULT 0 NOT NULL, M_AttributeSet_ID NUMERIC(10) DEFAULT NULL , M_AttributeSetInstance_ID NUMERIC(10) NOT NULL, M_FreightCategory_ID NUMERIC(10) DEFAULT NULL , M_Locator_ID NUMERIC(10) DEFAULT NULL , M_Product_Category_ID NUMERIC(10) NOT NULL, M_Product_ID NUMERIC(10) NOT NULL, Name VARCHAR(255) NOT NULL, Processing CHAR(1) DEFAULT ''N'', ProductType CHAR(1) DEFAULT ''I'' NOT NULL, R_MailText_ID NUMERIC(10) DEFAULT NULL , SalesRep_ID NUMERIC(10) DEFAULT NULL , S_ExpenseType_ID NUMERIC(10) DEFAULT NULL , ShelfDepth NUMERIC(10) DEFAULT NULL , ShelfHeight NUMBER DEFAULT NULL , ShelfWidth NUMERIC(10) DEFAULT NULL , SKU VARCHAR(30) DEFAULT NULL , S_Resource_ID NUMERIC(10) DEFAULT NULL , UnitsPerPack NUMERIC(10) DEFAULT NULL , UnitsPerPallet NUMBER DEFAULT NULL , UPC VARCHAR(30) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, VersionNo VARCHAR(20) DEFAULT NULL , Volume NUMBER DEFAULT NULL , Weight NUMBER DEFAULT NULL , CONSTRAINT M_Product_Key PRIMARY KEY (M_Product_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50235
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE WS_WebServiceTypeAccess (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Role_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsReadWrite CHAR(1) DEFAULT ''Y'' CHECK (IsReadWrite IN (''Y'',''N'')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WS_WebServiceTypeAccess_ID NUMERIC(10) NOT NULL, WS_WebServiceType_ID NUMERIC(10) NOT NULL, CONSTRAINT WS_WebServiceTypeAccess_Key PRIMARY KEY (WS_WebServiceTypeAccess_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50237
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE C_OrderLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_OrgTrx_ID NUMERIC(10) DEFAULT NULL , C_Activity_ID NUMERIC(10) DEFAULT NULL , C_BPartner_ID NUMERIC(10) DEFAULT NULL , C_BPartner_Location_ID NUMERIC(10) NOT NULL, C_Campaign_ID NUMERIC(10) DEFAULT NULL , C_Charge_ID NUMERIC(10) DEFAULT NULL , C_Currency_ID NUMERIC(10) NOT NULL, C_Order_ID NUMERIC(10) NOT NULL, C_OrderLine_ID NUMERIC(10) NOT NULL, C_Project_ID NUMERIC(10) DEFAULT NULL , C_ProjectPhase_ID NUMERIC(10) DEFAULT NULL , C_ProjectTask_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_Tax_ID NUMERIC(10) NOT NULL, C_UOM_ID NUMERIC(10) NOT NULL, DateDelivered TIMESTAMP DEFAULT NULL , DateInvoiced TIMESTAMP DEFAULT NULL , DateOrdered TIMESTAMP NOT NULL, DatePromised TIMESTAMP DEFAULT NULL , Description VARCHAR(255) DEFAULT NULL , Discount NUMBER DEFAULT NULL , FreightAmt NUMBER NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDescription CHAR(1) DEFAULT ''N'' CHECK (IsDescription IN (''Y'',''N'')) NOT NULL, Line NUMERIC(10) NOT NULL, LineNetAmt NUMBER NOT NULL, Link_OrderLine_ID NUMERIC(10) DEFAULT NULL , M_AttributeSetInstance_ID NUMERIC(10) NOT NULL, M_Product_ID NUMERIC(10) DEFAULT NULL , M_Promotion_ID NUMERIC(10) DEFAULT NULL , M_Shipper_ID NUMERIC(10) DEFAULT NULL , M_Warehouse_ID NUMERIC(10) NOT NULL, PP_Cost_Collector_ID NUMERIC(10) DEFAULT NULL , PriceActual NUMBER NOT NULL, PriceCost NUMBER DEFAULT NULL , PriceEntered NUMBER NOT NULL, PriceLimit NUMBER NOT NULL, PriceList NUMBER NOT NULL, Processed CHAR(1) CHECK (Processed IN (''Y'',''N'')) NOT NULL, QtyDelivered NUMBER NOT NULL, QtyEntered NUMBER DEFAULT 1 NOT NULL, QtyInvoiced NUMBER NOT NULL, QtyLostSales NUMBER DEFAULT NULL , QtyOrdered NUMBER DEFAULT 1 NOT NULL, QtyReserved NUMBER NOT NULL, Ref_OrderLine_ID NUMERIC(10) DEFAULT NULL , RRAmt NUMBER DEFAULT NULL , RRStartDate TIMESTAMP DEFAULT NULL , S_ResourceAssignment_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, User1_ID NUMERIC(10) DEFAULT NULL , User2_ID NUMERIC(10) DEFAULT NULL , CONSTRAINT C_OrderLine_Key PRIMARY KEY (C_OrderLine_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50261
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE M_Locator (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) CHECK (IsDefault IN (''Y'',''N'')) NOT NULL, M_Locator_ID NUMERIC(10) NOT NULL, M_Warehouse_ID NUMERIC(10) NOT NULL, PriorityNo NUMERIC(10) DEFAULT 50 NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, Value VARCHAR(40) NOT NULL, X VARCHAR(60) NOT NULL, Y VARCHAR(60) NOT NULL, Z VARCHAR(60) NOT NULL, CONSTRAINT M_Locator_Key PRIMARY KEY (M_Locator_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50265
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE M_PriceList (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, BasePriceList_ID NUMERIC(10) DEFAULT NULL , C_Currency_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EnforcePriceLimit CHAR(1) CHECK (EnforcePriceLimit IN (''Y'',''N'')) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsDefault CHAR(1) CHECK (IsDefault IN (''Y'',''N'')) NOT NULL, IsMandatory CHAR(1) DEFAULT NULL  CHECK (IsMandatory IN (''Y'',''N'')), isPresentForProduct CHAR(1) DEFAULT NULL  CHECK (isPresentForProduct IN (''Y'',''N'')), IsSOPriceList CHAR(1) CHECK (IsSOPriceList IN (''Y'',''N'')) NOT NULL, IsTaxIncluded CHAR(1) CHECK (IsTaxIncluded IN (''Y'',''N'')) NOT NULL, M_PriceList_ID NUMERIC(10) NOT NULL, Name VARCHAR(60) NOT NULL, PricePrecision NUMERIC(10) DEFAULT 2 NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT M_PriceList_Key PRIMARY KEY (M_PriceList_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50233
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE M_DiscountSchemaBreak (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, BreakDiscount NUMBER NOT NULL, BreakValue NUMBER NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsBPartnerFlatDiscount CHAR(1) DEFAULT ''N'' CHECK (IsBPartnerFlatDiscount IN (''Y'',''N'')) NOT NULL, M_DiscountSchemaBreak_ID NUMERIC(10) NOT NULL, M_DiscountSchema_ID NUMERIC(10) NOT NULL, M_Product_Category_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) DEFAULT NULL , SeqNo NUMERIC(10) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT M_DiscountSchemaBreak_Key PRIMARY KEY (M_DiscountSchemaBreak_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50248
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE C_CashLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Amount NUMBER NOT NULL, CashType CHAR(1) DEFAULT ''E'' NOT NULL, C_BankAccount_ID NUMERIC(10) DEFAULT NULL , C_Cash_ID NUMERIC(10) NOT NULL, C_CashLine_ID NUMERIC(10) NOT NULL, C_Charge_ID NUMERIC(10) DEFAULT NULL , C_Currency_ID NUMERIC(10) DEFAULT NULL , C_Invoice_ID NUMERIC(10) DEFAULT NULL , C_Payment_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , DiscountAmt NUMBER DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsGenerated CHAR(1) DEFAULT ''N'' CHECK (IsGenerated IN (''Y'',''N'')), Line NUMERIC(10) NOT NULL, Processed CHAR(1) CHECK (Processed IN (''Y'',''N'')) NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, WriteOffAmt NUMBER DEFAULT NULL , CONSTRAINT C_CashLine_Key PRIMARY KEY (C_CashLine_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50251
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE M_DiscountSchemaLine (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_BPartner_ID NUMERIC(10) DEFAULT NULL , C_ConversionType_ID NUMERIC(10) NOT NULL, Classification VARCHAR(12) DEFAULT NULL , ConversionDate TIMESTAMP NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Group1 VARCHAR(255) DEFAULT NULL , Group2 VARCHAR(255) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, Limit_AddAmt NUMBER NOT NULL, Limit_Base CHAR(1) DEFAULT ''X'' NOT NULL, Limit_Discount NUMBER NOT NULL, Limit_Fixed NUMBER DEFAULT NULL , Limit_MaxAmt NUMBER NOT NULL, Limit_MinAmt NUMBER NOT NULL, Limit_Rounding CHAR(1) DEFAULT ''C'' NOT NULL, List_AddAmt NUMBER NOT NULL, List_Base CHAR(1) DEFAULT ''L'' NOT NULL, List_Discount NUMBER NOT NULL, List_Fixed NUMBER DEFAULT NULL , List_MaxAmt NUMBER NOT NULL, List_MinAmt NUMBER NOT NULL, List_Rounding CHAR(1) DEFAULT ''C'' NOT NULL, M_DiscountSchema_ID NUMERIC(10) NOT NULL, M_DiscountSchemaLine_ID NUMERIC(10) NOT NULL, M_Product_Category_ID NUMERIC(10) DEFAULT NULL , M_Product_ID NUMERIC(10) DEFAULT NULL , SeqNo NUMERIC(10) NOT NULL, Std_AddAmt NUMBER NOT NULL, Std_Base CHAR(1) DEFAULT ''S'' NOT NULL, Std_Discount NUMBER NOT NULL, Std_Fixed NUMBER DEFAULT NULL , Std_MaxAmt NUMBER NOT NULL, Std_MinAmt NUMBER NOT NULL, Std_Rounding CHAR(1) DEFAULT ''C'' NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT M_DiscountSchemaLine_Key PRIMARY KEY (M_DiscountSchemaLine_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50255
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE C_OrderTax (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, C_Order_ID NUMERIC(10) NOT NULL, C_OrderTax_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, C_Tax_ID NUMERIC(10) NOT NULL, IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsTaxIncluded CHAR(1) CHECK (IsTaxIncluded IN (''Y'',''N'')) NOT NULL, Processed CHAR(1) DEFAULT ''N'' CHECK (Processed IN (''Y'',''N'')) NOT NULL, TaxAmt NUMBER NOT NULL, TaxBaseAmt NUMBER NOT NULL, Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT C_OrderTax_Key PRIMARY KEY (C_OrderTax_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50257
;

-- Mar 20, 2015 8:43:24 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_ChangeLog (AD_ChangeLog_ID NUMERIC(10) NOT NULL, AD_Client_ID NUMERIC(10) NOT NULL, AD_Column_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Session_ID NUMERIC(10) NOT NULL, AD_Table_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EventChangeLog CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCustomization CHAR(1) CHECK (IsCustomization IN (''Y'',''N'')) NOT NULL, NewValue VARCHAR(2000) DEFAULT NULL , OldValue VARCHAR(2000) DEFAULT NULL , Record_ID NUMERIC(10) NOT NULL, Redo CHAR(1) DEFAULT NULL , TrxName VARCHAR(60) DEFAULT NULL , Undo CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_ChangeLog_Key PRIMARY KEY (AD_ChangeLog_ID, AD_Column_ID, AD_Session_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:24','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50282
;

-- Mar 20, 2015 8:43:25 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_PInstance (AD_Client_ID NUMERIC(10) DEFAULT NULL , AD_Org_ID NUMERIC(10) DEFAULT NULL , AD_PInstance_ID NUMERIC(10) NOT NULL, AD_Process_ID NUMERIC(10) NOT NULL, AD_User_ID NUMERIC(10) DEFAULT NULL , Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) DEFAULT NULL , ErrorMsg VARCHAR(2000) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')), IsProcessing CHAR(1) CHECK (IsProcessing IN (''Y'',''N'')) NOT NULL, IsSynchronized CHAR(1) DEFAULT NULL  CHECK (IsSynchronized IN (''Y'',''N'')), Record_ID NUMERIC(10) NOT NULL, Result NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP DEFAULT NULL , UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT AD_PInstance_Key PRIMARY KEY (AD_PInstance_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:25','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50283
;

-- Mar 20, 2015 8:43:25 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE SPS_ChangeLog (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, AD_Session_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, Description VARCHAR(255) DEFAULT NULL , EventChangeLog CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsCustomization CHAR(1) DEFAULT ''N'' CHECK (IsCustomization IN (''Y'',''N'')) NOT NULL, IsSynchronized CHAR(1) DEFAULT NULL  CHECK (IsSynchronized IN (''Y'',''N'')), NewValue VARCHAR(2000) DEFAULT NULL , OldValue VARCHAR(2000) DEFAULT NULL , Record_ID NUMERIC(10) NOT NULL, Redo CHAR(1) DEFAULT NULL , SPS_ChangeLog_ID NUMERIC(10) NOT NULL, SPS_Column_ID NUMERIC(10) DEFAULT NULL , SPS_Table_ID NUMERIC(10) DEFAULT NULL , TrxName VARCHAR(60) DEFAULT NULL , Undo CHAR(1) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT SPS_ChangeLog_Key PRIMARY KEY (AD_Session_ID, SPS_ChangeLog_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:25','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50284
;

-- Mar 20, 2015 8:43:25 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE AD_PInstance_Para (AD_Client_ID NUMERIC(10) DEFAULT NULL , AD_Org_ID NUMERIC(10) DEFAULT NULL , AD_PInstance_ID NUMERIC(10) NOT NULL, Created TIMESTAMP DEFAULT NULL , CreatedBy NUMERIC(10) DEFAULT NULL , Info VARCHAR(60) DEFAULT NULL , Info_To VARCHAR(60) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')), IsSynchronized CHAR(1) DEFAULT NULL  CHECK (IsSynchronized IN (''Y'',''N'')), ParameterName VARCHAR(60) DEFAULT NULL , P_Date TIMESTAMP DEFAULT NULL , P_Date_To TIMESTAMP DEFAULT NULL , P_Number NUMBER DEFAULT NULL , P_Number_To NUMBER DEFAULT NULL , P_String VARCHAR(255) DEFAULT NULL , P_String_To VARCHAR(255) DEFAULT NULL , SeqNo VARCHAR(22) NOT NULL, Updated TIMESTAMP DEFAULT NULL , UpdatedBy NUMERIC(10) DEFAULT NULL , CONSTRAINT AD_PInstance_Para_Key PRIMARY KEY (AD_PInstance_ID, SeqNo))',Updated=TO_TIMESTAMP('2015-03-20 20:43:25','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50285
;

-- Mar 20, 2015 8:43:25 PM VET
-- Spin-Suite-Contribution
UPDATE AD_Rule SET Script='CREATE TABLE SPS_SyncTable (AD_Client_ID NUMERIC(10) NOT NULL, AD_Org_ID NUMERIC(10) NOT NULL, Created TIMESTAMP NOT NULL, CreatedBy NUMERIC(10) NOT NULL, EventChangeLog CHAR(1) DEFAULT NULL , IsActive CHAR(1) DEFAULT ''Y'' CHECK (IsActive IN (''Y'',''N'')) NOT NULL, IsSynchronized VARCHAR(1) DEFAULT NULL , Record_ID NUMERIC(10) DEFAULT NULL , SPS_SyncTable_ID NUMERIC(10) NOT NULL, SPS_Table_ID NUMERIC(10) DEFAULT NULL , SyncRecord_ID NUMERIC(10) DEFAULT NULL , Updated TIMESTAMP NOT NULL, UpdatedBy NUMERIC(10) NOT NULL, CONSTRAINT SPS_SyncTable_Key PRIMARY KEY (SPS_SyncTable_ID))',Updated=TO_TIMESTAMP('2015-03-20 20:43:25','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE AD_Rule_ID=50286
;

-- Mar 20, 2015 8:47:07 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51054
;

-- Mar 20, 2015 8:47:14 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50558
;

-- Mar 20, 2015 8:47:14 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50558
;

-- Mar 20, 2015 8:47:15 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50558 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 8:47:18 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50583
;

-- Mar 20, 2015 8:49:29 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51058
;

-- Mar 20, 2015 8:49:37 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50562
;

-- Mar 20, 2015 8:49:37 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50562
;

-- Mar 20, 2015 8:49:37 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50562 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 8:49:41 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50587
;

-- Mar 20, 2015 8:52:40 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51053
;

-- Mar 20, 2015 8:52:44 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50557
;

-- Mar 20, 2015 8:52:44 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50557
;

-- Mar 20, 2015 8:52:44 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50557 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 8:52:53 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50582
;

-- Mar 20, 2015 8:54:28 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET Name='Create Table Mobile Tab',Updated=TO_TIMESTAMP('2015-03-20 20:54:28','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50208
;

-- Mar 20, 2015 8:54:28 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu_Trl SET IsTranslated='N' WHERE SPS_SyncMenu_ID=50208
;

-- Mar 20, 2015 8:54:36 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51056
;

-- Mar 20, 2015 8:54:39 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50560
;

-- Mar 20, 2015 8:54:39 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50560
;

-- Mar 20, 2015 8:54:39 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50560 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 8:54:43 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50585
;

-- Mar 20, 2015 8:58:39 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51055
;

-- Mar 20, 2015 8:58:44 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50559
;

-- Mar 20, 2015 8:58:44 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50559
;

-- Mar 20, 2015 8:58:45 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50559 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 8:58:48 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50584
;

-- Mar 20, 2015 8:59:49 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51057
;

-- Mar 20, 2015 8:59:53 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50561
;

-- Mar 20, 2015 8:59:53 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50561
;

-- Mar 20, 2015 8:59:54 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50561 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 8:59:58 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50586
;

-- Mar 20, 2015 9:00:58 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51059
;

-- Mar 20, 2015 9:01:03 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50563
;

-- Mar 20, 2015 9:01:03 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50563
;

-- Mar 20, 2015 9:01:03 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50563 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 9:01:05 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50588
;

-- Mar 20, 2015 9:01:30 PM VET
-- Spin-Suite-Contribution
UPDATE AD_UserQuery SET UpdatedBy=100,Updated=TO_TIMESTAMP('2015-03-20 21:01:30','YYYY-MM-DD HH24:MI:SS') WHERE AD_UserQuery_ID=50018
;

-- Mar 20, 2015 9:01:48 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50564
;

-- Mar 20, 2015 9:01:48 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50564
;

-- Mar 20, 2015 9:01:48 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50564 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 9:01:51 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51066
;

-- Mar 20, 2015 9:01:53 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50595
;

-- Mar 20, 2015 9:02:06 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause=NULL,Updated=TO_TIMESTAMP('2015-03-20 21:02:06','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50538
;

-- Mar 20, 2015 9:02:41 PM VET
-- Spin-Suite-Contribution
UPDATE AD_UserQuery SET UpdatedBy=100,Updated=TO_TIMESTAMP('2015-03-20 21:02:41','YYYY-MM-DD HH24:MI:SS') WHERE AD_UserQuery_ID=50018
;

-- Mar 20, 2015 9:03:01 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50567
;

-- Mar 20, 2015 9:03:01 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50567
;

-- Mar 20, 2015 9:03:01 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50567 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 9:03:10 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51062
;

-- Mar 20, 2015 9:03:13 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50591
;

-- Mar 20, 2015 9:03:34 PM VET
-- Spin-Suite-Contribution
UPDATE AD_UserQuery SET UpdatedBy=100,Updated=TO_TIMESTAMP('2015-03-20 21:03:34','YYYY-MM-DD HH24:MI:SS') WHERE AD_UserQuery_ID=50018
;

-- Mar 20, 2015 9:03:47 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50568
;

-- Mar 20, 2015 9:03:47 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50568
;

-- Mar 20, 2015 9:03:47 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50568 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 9:03:52 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51063
;

-- Mar 20, 2015 9:03:54 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50592
;

-- Mar 20, 2015 9:04:18 PM VET
-- Spin-Suite-Contribution
UPDATE AD_UserQuery SET UpdatedBy=100,Updated=TO_TIMESTAMP('2015-03-20 21:04:18','YYYY-MM-DD HH24:MI:SS') WHERE AD_UserQuery_ID=50018
;

-- Mar 20, 2015 9:04:29 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50571
;

-- Mar 20, 2015 9:04:29 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50571
;

-- Mar 20, 2015 9:04:30 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50571 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 9:04:37 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51067
;

-- Mar 20, 2015 9:04:39 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50596
;

-- Mar 20, 2015 9:04:57 PM VET
-- Spin-Suite-Contribution
UPDATE AD_UserQuery SET UpdatedBy=100,Updated=TO_TIMESTAMP('2015-03-20 21:04:57','YYYY-MM-DD HH24:MI:SS') WHERE AD_UserQuery_ID=50018
;

-- Mar 20, 2015 9:05:14 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50569
;

-- Mar 20, 2015 9:05:14 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50569
;

-- Mar 20, 2015 9:05:15 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50569 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 9:05:18 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51064
;

-- Mar 20, 2015 9:05:19 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50593
;

-- Mar 20, 2015 9:05:53 PM VET
-- Spin-Suite-Contribution
UPDATE AD_UserQuery SET UpdatedBy=100,Updated=TO_TIMESTAMP('2015-03-20 21:05:53','YYYY-MM-DD HH24:MI:SS') WHERE AD_UserQuery_ID=50018
;

-- Mar 20, 2015 9:06:11 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50572
;

-- Mar 20, 2015 9:06:11 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50572
;

-- Mar 20, 2015 9:06:12 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50572 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 9:06:15 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=51068
;

-- Mar 20, 2015 9:06:17 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50597
;

-- Mar 20, 2015 9:06:23 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause=NULL,Updated=TO_TIMESTAMP('2015-03-20 21:06:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50546
;

-- Mar 20, 2015 9:07:00 PM VET
-- Spin-Suite-Contribution
UPDATE AD_UserQuery SET UpdatedBy=100,Updated=TO_TIMESTAMP('2015-03-20 21:07:00','YYYY-MM-DD HH24:MI:SS') WHERE AD_UserQuery_ID=50018
;

-- Mar 20, 2015 9:07:36 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause=NULL,Updated=TO_TIMESTAMP('2015-03-20 21:07:36','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50453
;

-- Mar 20, 2015 9:10:07 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='IsDefinedForMobile=''Y''',Updated=TO_TIMESTAMP('2015-03-20 21:10:07','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50393
;

-- Mar 20, 2015 9:10:15 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Column where SPS_Column.AD_Column_ID = AD_Column_Trl.AD_Column_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:10:15','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50389
;

-- Mar 20, 2015 9:10:23 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists (select 1 from SPS_Column where SPS_Column.AD_Element_ID = AD_Element.AD_Element_ID) or exists (select 1 from AD_Process inner join AD_Process_Para on(AD_Process_Para.AD_Process_ID = AD_Process.AD_Process_ID) where AD_Process_Para.AD_Element_ID = AD_Element.AD_Element_ID and AD_Process.IsDefinedForMobile = ''Y'')',Updated=TO_TIMESTAMP('2015-03-20 21:10:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50390
;

-- Mar 20, 2015 9:10:31 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from AD_PrintFormat pf where pf.SPS_Table_ID Iis not null and pf.AD_PrintFormat_ID = AD_PrintFormatItem.AD_PrintFormat_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:10:31','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50401
;

-- Mar 20, 2015 9:10:39 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause=' exists(select 1 from SPS_Column where SPS_Column.AD_Element_ID = AD_Element.AD_Element_ID) or exists(select 1 from AD_Process inner join AD_Process_Para on(AD_Process_Para.AD_Process_ID = AD_Process.AD_Process_ID) where AD_Process_Para.AD_Element_ID = AD_Element_Trl.AD_Element_ID and AD_Process.IsDefinedForMobile = ''Y'')',Updated=TO_TIMESTAMP('2015-03-20 21:10:39','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50391
;

-- Mar 20, 2015 9:10:46 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from AD_PrintFormatItem pfi where pfi.AD_PrintFormatItem_ID = AD_PrintFormatItem_Trl.AD_PrintFormatItem_ID and exists(select 1 from AD_PrintFormat pf where pf.SPS_Table_ID is not null  pf.AD_PrintFormat_ID = pfi.AD_PrintFormat_ID))',Updated=TO_TIMESTAMP('2015-03-20 21:10:46','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50402
;

-- Mar 20, 2015 9:10:55 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Column sc where sc.AD_Reference_Value_ID = AD_Reference.AD_Reference_ID) or exists(select 1 from AD_Process p inner join AD_Process_Para pp on(pp.AD_Process_ID = p.AD_Process_ID) where pp.AD_Reference_Value_ID = AD_Reference.AD_Reference_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:10:55','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50412
;

-- Mar 20, 2015 9:11:02 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Menu m where m.AD_Process_ID = AD_Process_Para.AD_Process_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:11:02','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50406
;

-- Mar 20, 2015 9:11:11 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Column sc where sc.AD_Reference_Value_ID = AD_Ref_Table.AD_Reference_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:11:11','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50411
;

-- Mar 20, 2015 9:11:16 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from AD_Table inner join SPS_Table on AD_Table.AD_Table_ID = SPS_Table.AD_Table_ID where AD_Table.AD_Table_ID=AD_Tree.AD_Table_ID) and AD_Tree.TreeType = ''CU''',Updated=TO_TIMESTAMP('2015-03-20 21:11:16','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50420
;

-- Mar 20, 2015 9:11:23 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from AD_Ref_List rl where rl.AD_Ref_List_ID = AD_Ref_List_Trl.AD_Ref_List_ID and exists(select 1 from SPS_Column sc where sc.AD_Reference_Value_ID = rl.AD_Reference_ID))',Updated=TO_TIMESTAMP('2015-03-20 21:11:23','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50410
;

-- Mar 20, 2015 9:11:28 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_SyncMenu where SPS_SyncMenu.AD_RuleAfter_ID=AD_Rule.AD_Rule_ID or SPS_SyncMenu.AD_RuleBefore_ID=AD_Rule.AD_Rule_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:11:28','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50415
;

-- Mar 20, 2015 9:11:34 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Column sc where sc.AD_Reference_Value_ID = AD_Reference_Trl.AD_Reference_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:11:34','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50413
;

-- Mar 20, 2015 9:11:39 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Column sc where sc.AD_Reference_Value_ID = AD_Ref_List.AD_Reference_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:11:39','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50409
;

-- Mar 20, 2015 9:11:46 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Table t where t.SPS_Table_ID = AD_ReportView.SPS_Table_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:11:46','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50414
;

-- Mar 20, 2015 9:11:56 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Menu m inner join AD_Process_Para pp on(pp.AD_Process_ID = m.AD_Process_ID) where pp.AD_Process_Para_ID = AD_Process_Para_Trl.AD_Process_Para_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:11:56','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50407
;

-- Mar 20, 2015 9:12:05 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='IsDefinedForMobile = ''Y''',Updated=TO_TIMESTAMP('2015-03-20 21:12:05','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50405
;

-- Mar 20, 2015 9:12:17 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause=NULL,Updated=TO_TIMESTAMP('2015-03-20 21:12:17','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50424
;

-- Mar 20, 2015 9:12:22 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Menu m where m.AD_Process_ID = AD_Process_Trl.AD_Process_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:12:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50408
;

-- Mar 20, 2015 9:12:37 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from AD_Form where AD_Form.AD_Form_ID = AD_Form_Trl.AD_Form_ID and AD_Form.IsDefinedForMobile=''Y'')',Updated=TO_TIMESTAMP('2015-03-20 21:12:37','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50394
;

-- Mar 20, 2015 9:12:55 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists (select 1 from SPS_SyncMenu where SPS_SyncMenu.WS_WebServiceType_ID=WS_WebServiceTypeAccess.WS_WebServiceType_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:12:55','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50445
;

-- Mar 20, 2015 9:13:22 PM VET
-- Spin-Suite-Contribution
UPDATE SPS_SyncMenu SET WhereClause='exists(select 1 from SPS_Column where SPS_Column.AD_Column_ID = AD_Column.AD_Column_ID)',Updated=TO_TIMESTAMP('2015-03-20 21:13:22','YYYY-MM-DD HH24:MI:SS'),UpdatedBy=100 WHERE SPS_SyncMenu_ID=50388
;

-- Mar 20, 2015 9:21:51 PM VET
-- Spin-Suite-Contribution
UPDATE AD_UserQuery SET UpdatedBy=100,Updated=TO_TIMESTAMP('2015-03-20 21:21:51','YYYY-MM-DD HH24:MI:SS') WHERE AD_UserQuery_ID=50018
;

-- Mar 20, 2015 9:25:35 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=50693
;

-- Mar 20, 2015 9:25:37 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=50694
;

-- Mar 20, 2015 9:25:38 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=50695
;

-- Mar 20, 2015 9:25:39 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebService_Para WHERE WS_WebService_Para_ID=50696
;

-- Mar 20, 2015 9:25:44 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53724
;

-- Mar 20, 2015 9:25:45 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53725
;

-- Mar 20, 2015 9:25:45 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53726
;

-- Mar 20, 2015 9:25:45 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53727
;

-- Mar 20, 2015 9:25:46 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53728
;

-- Mar 20, 2015 9:25:46 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53729
;

-- Mar 20, 2015 9:25:46 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53730
;

-- Mar 20, 2015 9:25:46 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53731
;

-- Mar 20, 2015 9:25:47 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53732
;

-- Mar 20, 2015 9:25:47 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53733
;

-- Mar 20, 2015 9:25:47 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53734
;

-- Mar 20, 2015 9:25:47 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53735
;

-- Mar 20, 2015 9:25:48 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53736
;

-- Mar 20, 2015 9:25:48 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53737
;

-- Mar 20, 2015 9:25:48 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53738
;

-- Mar 20, 2015 9:25:48 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53739
;

-- Mar 20, 2015 9:25:49 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53740
;

-- Mar 20, 2015 9:25:49 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53741
;

-- Mar 20, 2015 9:25:49 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53742
;

-- Mar 20, 2015 9:25:49 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53743
;

-- Mar 20, 2015 9:25:50 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53744
;

-- Mar 20, 2015 9:25:50 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53745
;

-- Mar 20, 2015 9:25:51 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53746
;

-- Mar 20, 2015 9:25:51 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53747
;

-- Mar 20, 2015 9:25:51 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53748
;

-- Mar 20, 2015 9:25:51 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53749
;

-- Mar 20, 2015 9:25:52 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53750
;

-- Mar 20, 2015 9:25:52 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53751
;

-- Mar 20, 2015 9:25:52 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53752
;

-- Mar 20, 2015 9:25:52 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53753
;

-- Mar 20, 2015 9:25:53 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53754
;

-- Mar 20, 2015 9:25:53 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53755
;

-- Mar 20, 2015 9:25:53 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53756
;

-- Mar 20, 2015 9:25:53 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53757
;

-- Mar 20, 2015 9:25:54 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53758
;

-- Mar 20, 2015 9:25:54 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53759
;

-- Mar 20, 2015 9:25:54 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53760
;

-- Mar 20, 2015 9:25:54 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53761
;

-- Mar 20, 2015 9:25:55 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=53762
;

-- Mar 20, 2015 9:25:55 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceFieldOutput WHERE WS_WebServiceFieldOutput_ID=55599
;

-- Mar 20, 2015 9:26:05 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu_Trl WHERE SPS_SyncMenu_ID=50425
;

-- Mar 20, 2015 9:26:05 PM VET
-- Spin-Suite-Contribution
DELETE FROM SPS_SyncMenu WHERE SPS_SyncMenu_ID=50425
;

-- Mar 20, 2015 9:26:06 PM VET
-- Spin-Suite-Contribution
DELETE FROM AD_TreeNode WHERE Node_ID=50425 AND EXISTS (SELECT * FROM AD_Tree t WHERE t.AD_Tree_ID=AD_TreeNode.AD_Tree_ID AND t.AD_Table_ID=53501)
;

-- Mar 20, 2015 9:26:08 PM VET
-- Spin-Suite-Contribution
DELETE FROM WS_WebServiceType WHERE WS_WebServiceType_ID=50460
;

